Update authors_update.py
sympy/sympy pull request #11644
Opened 2016-09-22 12:49 UTC by devangkulshreshtha

Update authors_update.py to include the number of authors in the top paragraph of AUTHORS file

2016-09-23 22:24 UTC, smichr commented on bin/authors_update.py
> +header_extra = """There are total {authors_count} number of authors\n""".format(authors_count=len(git_people))
recommend:  """There are a total of {authors_count} authors.\n"""

2016-09-23 22:24 UTC, smichr requested changes

2016-09-24 01:17 UTC, smichr approved these changes

2016-09-24 01:18 UTC, smichr commented
Thanks for taking the initiative on this addition. It's in.

2016-09-24 01:18 UTC, merged

2016-09-24 18:10 UTC, devangkulshreshtha commented
Thanks for the help, @smichr !