Added links to Column named Filename in Release  #11702
sympy/sympy pull request #11716
Opened 2016-10-12 05:31 UTC by Lakshya1605

#11702

2016-10-14 15:36 UTC, asmeurer requested changes

2016-10-14 15:36 UTC, asmeurer commented on release/fabfile.py
> +    @contextmanger
You spelled this wrong.

2016-10-14 15:36 UTC, asmeurer commented on release/fabfile.py
> +        table.append("<a href=\""+"%s" % link + "\">")
You can string format the whole string, like `'<a href="%s">' % link`.

2016-10-20 17:57 UTC, asmeurer commented on release/fabfile.py
> +                    with a_href('https://github.com/sympy/sympy/releases/download/sympy-'+'%s' %version+'/'+'%s' %name):
Also here you can just use one string. `'https://github.com/sympy/sympy/releases/download/sympy-%s/%s' % (version, name)`.

2016-12-23 22:56 UTC, moorepants commented
@Lakshya1605 can you verify that this works.

2017-02-04 16:55 UTC, Abdullahjavednesar commented
@asmeurer Are the changes good? Is it working?

2017-06-27 21:21 UTC, merged