exceptions: Changed bare exception in str.py to explicit exception
sympy/sympy pull request #12000
Opened 2016-12-29 22:20 UTC by ayodejiige

The last exception in _print_RandomDomain() should be called when the
RandomDomain object doesn't have a set property which will raise an
IndexError

<If this pull request fixes an issue please indicate which issue by typing "Fixes #NNNN" below.>
This is a first commit for #11668

2017-01-10 21:44 UTC, asmeurer commented
Wouldn't the second case also raise AttributeError?

2017-01-11 03:40 UTC, ayodejiige commented
It raises an index error because the RandomDomain class and child classes have a set property.
` @property
    def set(self):
        return self.args[1]`
The index error will be raised in cases where self.args[1] doesn't exist.

2017-01-11 03:49 UTC, ayodejiige commented
I did notice that I wouldn't this case though:
```python
class ConditionalDomain(RandomDomain):
    ...
    @property
    def set(self):
        raise NotImplementedError("Set of Conditional Domain not Implemented")
   ...
```
I will add the code to catch that. Also, this is my first open source project and I was wondering if issues on this projects are typically fixed with one pull request and if it's fine to continuously push to a pull request.

2017-01-11 05:34 UTC, asmeurer commented
Please push to the same pull request.

2017-01-11 05:35 UTC, asmeurer commented
It would be better to refactor the code to not use try-except logic at all. The fact that `set` raises IndexError is not at all obvious and could change if the implementation changes. It would be better to do `hasattr` checks.

2017-01-20 15:24 UTC, ayodejiige commented
I will make the necessary changes. Thanks!

2017-09-23 07:02 UTC, gxyd commented
@asmeurer can you please see if the changes are apt? Seems like he did 'try' address the requested changes.

2017-09-27 05:04 UTC, gxyd commented
@nilabja10201992 would you like to review this pull request?

2017-09-27 05:14 UTC, nilabja10201992 commented
@gxyd sure Sure I'll review them btw should I work on the fixes that you mentioned yesterday?

2017-09-27 05:15 UTC, gxyd commented
Yes, you can work on that as well.

2017-09-27 05:16 UTC, nilabja10201992 commented
Okay :)

2017-09-27 05:58 UTC, asmeurer requested changes

2017-09-27 05:58 UTC, asmeurer commented on sympy/printing/pretty/pretty.py
> +            return None
I believe this should be `self._print(None)` to match what was there before.

2017-09-27 05:58 UTC, asmeurer commented on sympy/printing/str.py
> +            return None
Printers should not return None. The above case should be the `else` case.

2017-09-27 05:58 UTC, asmeurer commented on sympy/printing/latex.py
> +            return None
Same here.

2017-09-27 08:52 UTC, nilabja10201992 commented
@gxyd seems correct to me, as @asmeurer stated _else shouldn't return None_, otherwise, everything seems okay.

2017-09-30 06:02 UTC, gxyd commented
@ayodejiige can you please address the requested changes?

2017-10-01 18:04 UTC, gxyd commented
@nilabja10201992 would you like to make changes here as suggested by Aaron?
You would need to add 'remote' here. The main purpose could be figuring out how to push to some other 'remote', search for it over the web.

In any case, let me know if you need help.

2017-10-01 19:53 UTC, nilabja10201992 commented
@gxyd I've made changes to my local branch but cannot push to the remote branch. It says access denied.

2017-10-01 19:54 UTC, gxyd commented
I'll get back in the morning.

2017-10-02 05:37 UTC, gxyd commented
Can you paste output of `git remote -v` (running in SymPy root folder) here?

2017-10-02 06:10 UTC, nilabja10201992 commented
```
origin	https://github.com/nilabja10201992/sympy (fetch)
origin	https://github.com/nilabja10201992/sympy (push)
pb	https://github.com/ayodejiige/sympy (fetch)
pb	https://github.com/ayodejiige/sympy (push)
upstream	https://github.com/sympy/sympy (fetch)
upstream	https://github.com/sympy/sympy (push)
```

2017-10-02 06:15 UTC, gxyd commented
And first you do `git remote fetch ayodejiige`. And after that you do `git checkout -b 11668_bare_excepts ayodejiige/11668_bare_excepts` (may be you **didn't** execute this command)?

And make changes to `11668_bare_excepts` **not** to `ayodejiige/11668_bare_excepts`. And finally you do `git push ayodejiige 11668_bare_excepts` (may be you did this right).

2017-10-02 06:19 UTC, ylemkimon commented
@gxyd Only those with write access to main branch(`sympy/sympy`) can push commits to PR branch.

2017-10-02 06:32 UTC, nilabja10201992 commented
@gxyd when I'm trying to push using `git it push ayodejiige 11668_bare_excepts` I'm getting these errors
```
error: src refspec 11668_bare_excepts does not match any.
error: failed to push some refs to 'ayodejiige'

```

2017-10-02 06:45 UTC, gxyd commented
Okay, yes you can't do that. I think that can be done via `git cherry-pick ...` command https://git-scm.com/docs/git-cherry-pick . That would be sending in a new pull request, not pushing to this branch.

2017-10-02 15:25 UTC, nilabja10201992 commented
@gxyd can you please look at the changes here https://github.com/sympy/sympy/compare/master...nilabja10201992:pb?expand=1 , should I pull request?

2017-10-14 20:27 UTC, gxyd commented
I have fixed the requested changes. Will merge it when it passes the test.

2017-10-20 07:50 UTC, gxyd commented
Tests pass. Merging.

2017-10-20 07:50 UTC, merged