Doc solve
sympy/sympy pull request #12141
Opened 2017-02-08 17:12 UTC by Yathartha22

This PR is regarding [issue #7615](https://github.com/sympy/sympy/issues/7615).

2017-02-09 06:30 UTC, asmeurer requested changes

2017-02-09 06:30 UTC, asmeurer commented on .profile
> +export PATH="$PATH:/c/Python27"
Remove this file.

2017-02-09 06:30 UTC, asmeurer commented on sympy/solvers/solvers.py
> +    * to solve set of equations when **flag set to default values
This is unnecessary. The other examples already show this.

2017-02-09 06:30 UTC, asmeurer commented on sympy/solvers/solvers.py
> +    ** to get only desired value value if dict=True
There's no need to duplicate the example here. Just add an example to the above of accessing the solution. Something like

```
>>> sol = solve([x - 3, y - 1], dict=True)
>>> sol
[{x: 3, y: 1}]
>>> sol[0][x]
3
```

2017-02-09 06:30 UTC, asmeurer commented on sympy/solvers/solveset.py
> +    #Solve using Gauss-Jordan elimination
Don't remove the spaces after the comment symbol.

2017-02-09 06:31 UTC, asmeurer commented
Be sure to check the code quality tests (`./bin/test quality`) before commiting.

2017-02-10 02:27 UTC, Yathartha22 commented
@asmeurer I have made the changes. Please have a look

2017-02-10 04:14 UTC, asmeurer approved these changes

2017-02-10 04:15 UTC, asmeurer commented
Please try to use a more descriptive pull request title and more descriptive commit messages in the future. See https://github.com/sympy/sympy/wiki/Development-workflow#writing-commit-messages.

2017-02-10 04:15 UTC, merged

2017-02-10 04:44 UTC, Yathartha22 commented
Thanks @asmeurer this was my first contribution. I will definitely make more of better contributions, and surely keep in mind what you said :)