Typos fixed and link updated in `mathml.py`
sympy/sympy pull request #12401
Opened 2017-03-22 23:25 UTC by mamakancha

Two typos have been fixed.
And the link given in `Line 21` has been updated.

This PR also fixes #11986

2017-03-24 18:15 UTC, mamakancha commented
@jksuom Can you please restart the falling **Theano** test?

2017-03-25 15:51 UTC, aktech requested changes

2017-03-25 15:51 UTC, aktech commented on sympy/printing/mathml.py
> +        #denominator
comment should start with a `#` and a "single space".

2017-03-28 22:39 UTC, mamakancha commented on sympy/printing/mathml.py
> +        #denominator
Thanks for pointing out! Done :)

2017-03-31 01:14 UTC, mamakancha commented
`./bin/test test_refine.py` seems to take a lot of time and hence leads to termination of the test. What could be the possible reason for this due to the edits?

2017-03-31 18:28 UTC, mamakancha commented
ping @aktech @jksuom

2017-04-05 12:16 UTC, smichr commented
It's in. Thanks!

2017-04-05 12:16 UTC, merged