Guard against recursion error in _can_print_latex
sympy/sympy pull request #12445
Opened 2017-03-28 23:06 UTC by mamakancha

Since versions of Python before `Python 3.5` do not support RecursionError. So, we need to check for RuntimeError to support the lower Python versions.
Fixes #12444

2017-03-29 19:01 UTC, asmeurer requested changes

2017-03-29 19:01 UTC, asmeurer commented on sympy/interactive/printing.py
> +        except:
This should be except RuntimeError

2017-03-29 19:01 UTC, asmeurer commented on sympy/interactive/printing.py
> +            print("RuntimeError: maximum recursion depth exceeded in comparison")
The correct thing to do here is to return False, not print anything.

2017-03-31 14:13 UTC, mamakancha commented
@asmeurer Requested changes implemented. Please review :)

2017-04-03 21:46 UTC, asmeurer approved these changes

2017-04-03 21:46 UTC, merged