Removed Backslashes Fixes #12441
sympy/sympy pull request #12442
Opened 2017-03-28 16:29 UTC by rajatthakur

I have removed all unnecessary backslashes from the codebase.

Thanks :smile:

2017-03-28 22:06 UTC, siefkenj requested changes

2017-03-28 22:06 UTC, siefkenj commented on sympy/polys/tests/test_ring_series.py
> +                                                     1))*x**3*y - EX((3*a**2 + 1)/(3*a**6 - 9*a**4 + 9*a**2 - 3))*x**3 - \
These lines have not become more readable...

2017-03-28 22:06 UTC, siefkenj commented on sympy/polys/tests/test_numberfields.py
> +                                                          (1 + x**(-3))**(S(3)/2)) + 1/(x**(S(11)/2)*(1 + x**(-3))**(S(3)/2))
Why the extra space in front?  This was broken up into two lines to try and keep the line-length down.

2017-09-25 05:30 UTC, gxyd commented
@rajatthakur I am -1 to the changes introduced in this PR.

2017-09-25 05:31 UTC, closed without merging