Issue 12544  Sum(cos(1/n) - 1, (n, 1, oo)).is_convergent() issue
sympy/sympy pull request #12553
Opened 2017-04-16 18:25 UTC by maurogaravello

The series of `cos(1/n) - 1` is convergent, but the
`is_convergent()` method return false.
To fix this issue, a function for finding the asymptotic behavior
is implemented.

The changes are in `summation.py`.
A test is added.

"Fixes #12544 "

2017-04-16 20:35 UTC, asmeurer commented on sympy/concrete/summations.py
> +    if type(expr) is Mul:
Use `isinstance` to check types.

2017-04-16 20:37 UTC, asmeurer requested changes

2017-04-16 20:37 UTC, asmeurer commented on sympy/concrete/summations.py
> +    except:
Don't use bare excepts. Catch only the exception you are expecting.

2017-04-16 20:37 UTC, asmeurer commented on sympy/concrete/summations.py
> +    '''Tries to perform the asymptotic of expr when
asymptotic expansion?

2017-04-16 20:37 UTC, asmeurer commented on sympy/concrete/summations.py
> +from sympy.core.add import Add, Mul
Mul should come from sympy.core.mul.

2017-04-17 08:28 UTC, maurogaravello commented on sympy/concrete/summations.py
> +    '''Tries to perform the asymptotic of expr when
Not always is an expansion. Probably 'asymptotic bahavior' is better

2017-04-17 08:30 UTC, maurogaravello commented on sympy/concrete/summations.py
> +    except:
I put `except Exception:`. I am not sure if it is ok. I tried with `except NotImplementedError:`, but some tests failed.

2017-04-17 12:22 UTC, maurogaravello commented
In the case log(n/(n+1)) the method asymptotic does not work correctly. I will try to fix.

2017-04-23 10:14 UTC, maurogaravello commented
@asmeurer What do you think with this PR?

2017-05-04 13:00 UTC, maurogaravello commented on sympy/concrete/summations.py
> +    if type(expr) is Mul:
Done

2017-05-04 13:00 UTC, maurogaravello commented on sympy/concrete/summations.py
> +from sympy.core.add import Add, Mul
Done

2018-07-28 14:10 UTC, closed without merging