Updated Matrix.dot() Docstring
sympy/sympy pull request #12726
Opened 2017-06-09 21:51 UTC by ddjr

Updated Matrix.dot() Docstring by adding parameters as well as updating variable names with `` notation.

2017-06-12 02:44 UTC, siefkenj requested changes

2017-06-12 02:44 UTC, siefkenj commented on Untitled.ipynb
> +{
You shouldn't be committing this file.

2017-06-12 02:44 UTC, siefkenj commented on sympy/matrices/matrices.py
> +        the same as the length of ``b`` then the dot product is returned. If self
If you're double quoting `self`, double quote all instances.

2017-09-26 02:51 UTC, gxyd commented
@ddjr can you please address the requested changes?

2017-10-14 20:49 UTC, gxyd commented
This PR has been inactive for quite sometime, so we are going to close it and open an issue to reference it. We try to keep our pull request queue small and focused on active work.  We encourage you to reopen the pull request if and when you continue to work on this. Please contact us if you have any questions.

Thanks for contributing.

see https://github.com/sympy/sympy/wiki/Closing-pull-requests for our policies on closing pull request.

I've opened https://github.com/sympy/sympy/issues/13449 for this pull request so that we don't forget about it.

2017-10-14 20:49 UTC, closed without merging