Deprecation warnings to 'densearith.py' 'densetools.py' 'densesolve.py'
sympy/sympy pull request #12768
Opened 2017-06-18 00:24 UTC by firedranzer

Added test_deprecated() function to fix the tests to handle the deprecation warnings.#12695

Also renamed jordan_cell and jordan_cells with the more commonly used words jordan_block and jordan_blocks.#12685

2017-06-18 04:00 UTC, siefkenj requested changes
In `densearith.py` etc, right after the imports, you should raise a deprecation warning.  That way, if the file ever gets imported, a deprecation warning is raised.  You'll need to catch this warning in the import statements in the relevant test files.

2017-06-18 04:00 UTC, siefkenj commented on sympy/matrices/dense.py
> +def jordan_block(eigenval, n):
We need to include the deprecated version of this function as well and wrap it with the deprecation decorator.

2017-06-18 04:00 UTC, siefkenj commented on sympy/matrices/dense.py
> +    Create matrix of Jordan block kind:
Change to "Create a Jordan block"

2017-06-18 04:00 UTC, siefkenj commented on sympy/matrices/densearith.py
> +def test_deprecated():
This test belongs in the `test_densearith.py` file

2017-06-18 04:00 UTC, siefkenj commented on sympy/matrices/densesolve.py
> +def test_deprecated():
Tests in the test files

2017-06-18 04:00 UTC, siefkenj commented on sympy/matrices/densetools.py
> +def test_deprecated():
Tests in the test files

2017-06-18 06:39 UTC, firedranzer commented on sympy/matrices/dense.py
> +def jordan_block(eigenval, n):
@siefkenj Do you mean we have to use the same kind of deprecated function that we used in other files ?

2017-06-18 14:32 UTC, siefkenj commented on sympy/matrices/dense.py
> +def jordan_block(eigenval, n):
I mean that `from matrices.dense import jordan_cell` must still work, but it should raise a deprecation warning.

2017-06-18 14:35 UTC, siefkenj commented
As a side note, you should make all changes and then commit and push.  There should be one commit per feature instead of one commit per changed line.  Also, you can run tests locally with 

```
python -c "import sympy; sympy.test('sympy/matrices', slow=False)"
```

for instance (from the sympy directory).  It's a lot faster than waiting for Travis to run the tests.

2017-06-18 18:48 UTC, firedranzer commented
Thanks @siefkenj . I'm new to open source and learning the way things work here .I'll remember these points from the next time.

2017-06-18 20:29 UTC, firedranzer commented on sympy/matrices/dense.py
> +def jordan_block(eigenval, n):
I did not find `from matrices.dense import jordan_cell` in dense.py . I am stuck at this.Need your help @siefkenj .

2017-06-18 20:38 UTC, siefkenj commented
@firedranzer So far, it doesn't look like any of this PR is usable and it is getting a little messy.  I would close it an open a new PR that does the following 3 things:

  1. Add a deprecation warning to `jordan_cells`.  Look at the `MatrixDeprecated` class in `matrices.py` for how to do this.
  2. Raise a warning immediately after the import statements in `matrixarith.py` etc.  Look through `matrices.py` for a deprecated kwarg and do something similar.  For example `rankcheck` in the LU decomposition should raise a warning if it is set to `True`.
  3. wrap the `from matrixarith import ...` statements in the `test_matrixarith.py` etc. files with the `with warnings.warn...` syntax.

Welcome to open source.  It'll take a little practice to get on your feed, but we're glad to have you hear!

2017-06-20 17:52 UTC, firedranzer commented
@siefkenj I am altogether facing a lot of issues. I guess, I'll start a fresh pull request soon.I might be able to come up with a workaround later (when I'm more experienced with deprecation warnings and stuff). Till then, I guess this is pretty much the contribution on the issue from my side.

2017-06-30 05:04 UTC, closed without merging