[WIP] implementing transolve
sympy/sympy pull request #13045
Opened 2017-07-26 12:03 UTC by Yathartha22

In this PR I have tried to implement `transolve` to make it work for `logarithmic and exponential equations`.
Initial commit was made in [PR](https://github.com/sympy/sympy/pull/11540). I have modified and reimplemented a bit so that it works and also added few `test cases`.

- [x] logarithmic equations
- [x] exponential equations
- [ ] equations solvable by LambertW function
- [ ] implementing trigonometric equation solver
 
ping @asmeurer @smichr @jksuom  @aktech @Shekharrajak @kshitij10496

2017-07-26 13:34 UTC, aktech commented
Please cherry-pick the commit from #11540 to retain authorship, instead of a new commit.

2017-07-26 18:10 UTC, Yathartha22 commented
I haven't used cherry-pick before, could you please help me with this.
I followed this [answer](https://stackoverflow.com/a/1405189/6446166) of StackOverflow as a reference.
[This](https://github.com/Yathartha22/sympy/blob/test/sympy/solvers/solveset.py#L791) is what the changes look like. I am not sure about it.

2017-07-28 07:21 UTC, Yathartha22 commented
@aktech I have made the changes as you suggested. Please have a look.

2017-08-01 14:47 UTC, Shekharrajak commented on sympy/solvers/tests/test_solveset.py
> +    assert solveset(4**(5-9*x) - 8**(2-x), x, S.Reals) == FiniteSet(Rational(4, 15))
Can you write test cases for complex solutions as well ?

2017-08-01 15:22 UTC, Yathartha22 commented on sympy/solvers/tests/test_solveset.py
> +    assert solveset(4**(5-9*x) - 8**(2-x), x, S.Reals) == FiniteSet(Rational(4, 15))
Well, as of now I haven't made it to work for complex domain. I will be making few changes in `_invert_complex` and then add the test cases.

2017-08-03 11:45 UTC, Yathartha22 commented
@Shekharrajak I have added few test cases for complex solutions as well. Please have a look.

2017-09-08 03:43 UTC, Yathartha22 commented
@smichr @asmeurer @jksuom

2017-10-25 18:34 UTC, Yathartha22 commented
#11096 should be taken care while implementing exponential solver.

2018-03-24 20:45 UTC, aktech commented
@Yathartha22 Can you please fix conflicts?

2018-03-24 22:07 UTC, aktech requested changes

2018-03-24 22:07 UTC, aktech commented on sympy/solvers/solveset.py
> +        if not g and not g_ys.args[0] and len(h.args) == 2 and \
In a system like solvers where almost everything is heuristics, these conditions don't makes sense easily and would slowly get out of hand after multiple iterations of code changes over time. This is one of the reasons why `solve` is hard to understand.

To handle this situation, I would suggest to first document the what, why and how each and every condition and its proof of correctness, that would help in further development and extension. You also need to write meaningful functions wherever there is an independent piece/logic of code, which may or may not change to incorporate changes/addition of more conditions or situations to handle more equations.

2018-06-06 20:32 UTC, aktech commented
Closing in favor of #14736

2018-06-06 20:32 UTC, closed without merging