Update docs for intpoly module
sympy/sympy pull request #13229
Opened 2017-08-31 09:17 UTC by ArifAhmed1995

Adds a section for the newly created `intpoly` module.

2017-09-06 21:52 UTC, ArifAhmed1995 commented
@certik Can you review please ? Should I add more examples ?

2017-09-06 21:58 UTC, certik commented
@ArifAhmed1995 thank you for writing it up. I would also add there something along the lines of:
```
Uses evaluation techniques as described in Chin et al(2015)[1]
References
===========
[1] : http://dilbert.engr.ucdavis.edu/~suku/quadrature/cls-integration.pdf
```
so that people know where to get more information. However, please fix the citation at both places to:

Chin, Eric B., Jean B. Lasserre, and N. Sukumar. "Numerical integration of homogeneous functions on convex and nonconvex polygons and polyhedra." Computational Mechanics 56.6 (2015): 967-981.

As that is the correct way to cite the paper. The pdf location might change.

2017-09-06 22:20 UTC, ArifAhmed1995 commented
@certik Is it fine now ?

2017-09-06 22:51 UTC, certik requested changes
Thanks. Few more minor comments.

2017-09-06 22:51 UTC, certik commented on doc/src/modules/integrals/integrals.rst
> +Uses evaluation techniques as described in Chin et al(2015)[1]
`Chin et al. (2015) [1].`. Notice the dot after `al.`.

2017-09-06 22:51 UTC, certik commented on sympy/integrals/intpoly.py
Chin et al. (2015) [1].

2017-09-07 03:41 UTC, certik commented
You have to put the dot after `al.`, because `et al.` is an abbreviation from Latin `et alii`, meaning "and others".

2017-09-07 03:46 UTC, ArifAhmed1995 commented
Is it fine now ? I just updated the PR.

2017-09-07 03:59 UTC, certik approved these changes

2017-09-07 04:00 UTC, certik commented
Yes, that looks good now. +1 to merge. Please ping me once tests pass, so that I can merge.

2017-09-07 12:49 UTC, ArifAhmed1995 commented
@certik I don't why that test fails on Travis. It runs fine locally. Maybe a restart would help.
This is the job : https://travis-ci.org/sympy/sympy/jobs/272747201

2017-09-07 14:25 UTC, certik commented
I restarted the job. It seems unrelated to this PR.

2017-09-07 15:40 UTC, ArifAhmed1995 commented
@certik Did the test fail again as well or is the restart in queue and hasn't happened yet ?

2017-09-07 15:56 UTC, certik commented
@ArifAhmed1995 it's caused by #13270. Let me see how to fix it.

2017-09-07 16:01 UTC, certik commented
I merged a fix into master, and rebased your PR on top of the latest master. All tests should now pass. @ArifAhmed1995 please ping me once they do, so that I can merge this.

2017-09-07 18:55 UTC, ArifAhmed1995 commented
@certik The tests finally pass now...

2017-09-07 18:58 UTC, merged

2017-09-07 18:58 UTC, certik commented
Perfect, thanks!

2017-09-10 04:44 UTC, ArifAhmed1995 commented
@certik I can't see this new section on the SymPy docs page. Will it be there once the next release is done ?

2017-09-10 11:46 UTC, gxyd commented
They are present in `dev` not in `latest`, here is the link http://docs.sympy.org/dev/modules/integrals/integrals.html . Also I think Aaron does the re-building of the docs manually himself after a few days may be.

2017-09-10 11:48 UTC, ArifAhmed1995 commented
@gxyd Oh I see. Thank you for explaining !