integrals/intpoly : Feature to compute integrals for list of polynomials up to max_degree
sympy/sympy pull request #13254
Opened 2017-09-03 21:31 UTC by ArifAhmed1995

This PR adds the feature of being able to compute integrals of a list of polynomials over a 3-Polytope.

2017-09-03 21:55 UTC, ArifAhmed1995 commented
@certik Review please. Once this is merged I'll update this PR as well : [#13229](https://github.com/sympy/sympy/pull/13229)

2017-09-04 02:45 UTC, certik requested changes
Otherwise I think it looks good.

2017-09-04 02:45 UTC, certik commented on sympy/integrals/tests/test_intpoly.py
> +        {y * z: 3125 / 4, x ** 2: 3125 / 3}
3125 / S(4), ...

2017-09-04 02:45 UTC, certik commented on sympy/integrals/tests/test_intpoly.py
> +         x ** 2: 3125 / 3}
The same here.

2017-09-04 10:21 UTC, ArifAhmed1995 commented
@certik Is it fine now ?

2017-09-04 14:57 UTC, certik requested changes
You forgot one. Otherwise it looks good.

2017-09-04 14:57 UTC, certik commented on sympy/integrals/tests/test_intpoly.py
> +         y * z: 3125 / S(4), z ** 2: 3125 / S(3), y ** 2: 3125 / 3,
This should be `3125 / S(3)`.

2017-09-04 16:43 UTC, certik approved these changes
Thanks for fixing the other fractions as well. I have no more comments. +1 to merge if tests pass.

@ArifAhmed1995 please ping me once the tests succeed, so that I can merge it.

2017-09-05 02:40 UTC, ArifAhmed1995 commented
@certik The tests pass now.

2017-09-05 21:30 UTC, merged