convert expr.func is xyz to isinstance(expr,xyz)
sympy/sympy pull request #13357
Opened 2017-09-27 09:43 UTC by nilabja10201992

Fixes to issues as mentioned in issue #13111 and as per discussion in issue #13342

2017-09-27 12:00 UTC, ylemkimon requested changes

2017-09-27 12:00 UTC, ylemkimon commented on sympy/core/expr.py
> +			if isinstance(arg,exp_polar):
Use 4 spaces instead of tab and space after comma. (Same for below)

2017-09-27 12:00 UTC, ylemkimon commented on sympy/core/mod.py
> +		elif isinstance((-p),cls):
Parenthesis is not necessary for function arguments.

2017-09-28 01:56 UTC, ylemkimon requested changes

2017-09-28 01:56 UTC, ylemkimon commented on sympy/core/power.py
> +                if not e.is_Atom and b is not S.Expl and not(instance(b,exp_polar)):
It is `Exp1`(the number one, not alphabet l) and did you mean `not isinstance(b, exp_polar)`?

2017-09-28 01:56 UTC, ylemkimon commented on sympy/core/mod.py
> +        elif isinstance((-p), cls):
You can do `isinstance(-p, cls)`.

2017-09-28 04:54 UTC, gxyd commented
You can try to fix all the `is` comparison issues in this pull request. You can do `git grep -E 'func is'` in SymPy root folder to get a list of (possibly) all such issues.

2017-09-28 05:09 UTC, nilabja10201992 commented
@gxyd Why are Travis checks failing?

2017-09-28 05:23 UTC, gxyd commented
Don't worry about that. They failed on the past few builds, but on the latest build tests seems to be passing. Here they, passed :)

2017-09-28 06:19 UTC, nilabja10201992 commented
@gxyd I'll make changes to all files where changes can be made (there are lots of files where it can be implemented), thank you for guiding.

2017-09-28 09:08 UTC, ylemkimon commented
I think `x.func is type` in the tests can be left as is.

2017-09-28 09:56 UTC, nilabja10201992 commented
@ylemkimon okay I'll make changes only if the file isn't in test folder of sympy.

2017-09-29 07:08 UTC, ylemkimon requested changes

2017-09-29 07:08 UTC, ylemkimon commented on sympy/functions/elementary/trigonometric.py
> +        if isinstance(arg,asin):
Space after comma

2017-09-29 07:08 UTC, ylemkimon commented on sympy/functions/special/error_functions.py
> +        if (isinstance(z, erf)) and z.args[0].is_real:
The parenthesis surrounding isinstance is unnecessary. Same for below.

2017-09-29 12:19 UTC, ylemkimon commented on sympy/functions/special/error_functions.py
> +        if nz is not None and ((isinstance(nz, erf)) and (nz.args[0]).is_real):
The parenthesis surrounding isinstance is unnecessary.

2017-09-29 12:26 UTC, ylemkimon commented
There seems some `expr.func is type` left.
```python
sympy/concrete/expr_with_limits.py:27:    if hasattr(function, 'func') and function.func is Equality:
sympy/core/power.py:641:        if old.func is self.func and self.exp == old.exp:
sympy/core/power.py:646:        if old.func is self.func and self.base == old.base:
sympy/functions/special/zeta_functions.py:163:        if z.func is exp and (z.args[0]/(pi*I)).is_Rational or z in [-1, I, -I]:
sympy/integrals/deltafunctions.py:55:        if arg.is_Pow and arg.base.func is DiracDelta:
sympy/integrals/deltafunctions.py:67:            elif arg.is_Pow and arg.base.func is DiracDelta:
sympy/integrals/integrals.py:773:        if f.func is Piecewise:
sympy/integrals/risch.py:306:            if (i.base.is_Pow or i.base.func is exp and i.exp.is_Rational)]
sympy/logic/algorithms/dpll.py:283:                P, value = sym, not (literal.func is Not)
sympy/logic/boolalg.py:1069:    if info[0].func is info[2]:
sympy/logic/boolalg.py:1071:            if arg.func is info[1]:
sympy/logic/boolalg.py:1079:    elif info[0].func is info[1]:
sympy/logic/boolalg.py:1272:    if expr.func is function2:
sympy/logic/boolalg.py:1287:    if expr.func is not function1:
sympy/logic/boolalg.py:1296:        elif cls.func is not function2:
sympy/series/gruntz.py:278:        if e.args[0].func is log:
sympy/simplify/fu.py:326:                any(any(ai.func is cos or ai.is_Pow and ai.base is cos
sympy/simplify/fu.py:382:                    k.args[1].func is cos:
sympy/simplify/fu.py:1482:        if not (isinstance(rv, Pow) and rv.base.func is sin):
sympy/simplify/fu.py:1511:        if not (isinstance(rv, Pow) and rv.base.func is cos):
sympy/simplify/fu.py:1544:        if rv.base.func is tan:
sympy/simplify/fu.py:1546:        elif rv.base.func is sin:
sympy/simplify/fu.py:1548:        elif rv.base.func is cos:
sympy/simplify/fu.py:1931:        if c.func is not s.func:
sympy/simplify/fu.py:1937:                if not ((ca.func is sa.func) is (cb.func is sb.func)):
sympy/simplify/fu.py:1942:                return gcd, n1, n2, ca.args[0], sa.args[0], ca.func is sa.func
sympy/simplify/powsimp.py:678:        if glogb.args[0].is_Pow or glogb.args[0].func is exp:
sympy/solvers/ode.py:2273:                if newi.lhs.func is log and newi.rhs == 0:
sympy/solvers/ode.py:2656:        if expr.func is Add:
sympy/solvers/ode.py:2678:    if expr.func is Equality:
sympy/solvers/ode.py:2681:        if lhs.func is Symbol and lhs in Cs:
sympy/solvers/ode.py:2814:                if m.func is exp:
sympy/solvers/ode.py:2817:                    infac = any(fi.func is exp for t in m.args
```

Thank you!

2017-09-29 12:32 UTC, nilabja10201992 commented
@ylemkimon the ode.py file is commented there is no code where it can be implemented. And in case of fu.py the statements are like rv.base.func is tan, if I change it to isinstance(rv.base, tan) will it cause some unnecessary  problem? I'll look into that and make the changes and I'll wait for your reply.

2017-09-29 12:41 UTC, smichr commented on sympy/integrals/deltafunctions.py
>              elif arg.is_Pow and arg.base.func is DiracDelta:
It is perhaps worth checking again for `.func is ` to see if any others (like this one) got missed.

2017-09-29 12:42 UTC, smichr commented on sympy/logic/boolalg.py
>      if expr.func is function2:
here's another that got missed

2017-09-29 12:42 UTC, smichr commented on sympy/logic/boolalg.py
>          elif cls.func is not function2:
another

2017-09-29 12:42 UTC, smichr commented on sympy/series/gruntz.py
>          if e.args[0].func is log:
another

2017-09-29 12:43 UTC, smichr commented on sympy/simplify/fu.py
>          if c.func is not s.func:
another (but this one should be `if not isinstance(c.func, s.func)`

2017-09-29 12:44 UTC, smichr commented on sympy/simplify/powsimp.py
>          if glogb.args[0].is_Pow or glogb.args[0].func is exp:
another

2017-09-29 12:45 UTC, ylemkimon commented
I missed the comments, sorry. `rv.base.func is tan` and similar can be safely converted to `isinstance(rv.base, tan)` since it is equivalent to `(rv.base).func`.

2017-09-29 15:59 UTC, nilabja10201992 commented
@ylemkimon @smichr` if not ((ca.func is sa.func) is (cb.func is sb.func)):`
will `if not isinstance(isinstacnce(ca, sa.func), isinstance(cb,sb.func)):` be a solution to reduce this?

2017-09-29 21:13 UTC, smichr commented
> if not (isinstacnce(ca, sa.func) is isinstance(cb,sb.func)):

That should work, but I would write it with the `not` in the middle:

```
if isinstance(ca, sa.func) is not isinstance(cb, sb.func):
```

2017-09-30 01:18 UTC, ylemkimon commented
There seems one more at [sympy/functions/special/zeta_functions.py#L163](https://github.com/nilabja10201992/sympy/blob/2fa80c56468cb7647ec6731a7c5bdb14cb5dde4a/sympy/functions/special/zeta_functions.py#L163) and some at `ode.py`:
```
sympy/solvers/ode.py:2656:        if expr.func is Add:
sympy/solvers/ode.py:2678:    if expr.func is Equality:
sympy/solvers/ode.py:2681:        if lhs.func is Symbol and lhs in Cs:
sympy/solvers/ode.py:2814:                if m.func is exp:
sympy/solvers/ode.py:2817:                    infac = any(fi.func is exp for t in m.args
```

2017-09-30 12:52 UTC, smichr commented
Thanks! This is in. Hopefully this won't break too many PRs but this is something that we've said that should be done. So...no better time than today!

2017-09-30 12:56 UTC, merged

2017-09-30 12:56 UTC, smichr commented
Thanks, @ylemkimon , for the printouts of where more of these were.

2017-10-01 11:07 UTC, nilabja10201992 commented
@gxyd @ylemkimon @smichr please suggest some issue that I can work on, "easy fixes" in issues section is too outdated. Thank You.