issue_13651
sympy/sympy pull request #13673
Opened 2017-12-05 04:44 UTC by Subhash-Saurabh

2017-12-06 14:27 UTC, gxyd commented
Please read this https://github.com/sympy/sympy/wiki/Development-workflow#title-summary and https://github.com/sympy/sympy/wiki/Development-workflow#writing-commit-messages

You can use triple quotes (I did for now) to better format the code in the description https://guides.github.com/features/mastering-markdown/

2017-12-06 19:15 UTC, asmeurer commented on sympy/printing/latex.py
> +            if self._needs_add_brackets(term) or term.is_Add:
It seems this check should be in _needs_add_brackets itself.

2017-12-07 06:48 UTC, Subhash-Saurabh commented
@asmeurer  I have made the changes you suggested .Can you please review it now.

2017-12-07 07:43 UTC, gxyd requested changes

2017-12-07 07:43 UTC, gxyd commented on sympy/printing/tests/test_latex.py
> +    from sympy.abc import a,b,c
Symbols 'a, 'b' and 'c' are defined at the top of file.

2017-12-07 07:43 UTC, gxyd commented on sympy/printing/tests/test_latex.py
Add one more empty new line here for consistency.

2017-12-07 07:43 UTC, gxyd commented on sympy/printing/tests/test_latex.py
> +    bug = c+collect_const(-a-b)
`bug` isn't a good variable name. Also use space `-a - b` and `c + ...`

2017-12-07 07:43 UTC, gxyd commented on sympy/printing/tests/test_latex.py
Add one more empty new line here for consistency.

2017-12-07 07:45 UTC, gxyd commented
Also address this comment

https://github.com/sympy/sympy/pull/13673#issuecomment-349654990

2017-12-07 11:29 UTC, gxyd commented
On your branch:
```python
>>> import sympy
>>> from sympy.abc import a, b, c
>>> buggy = c + sympy.collect_const(-a - b)
>>> sympy.pprint(buggy)
c - a + b
```

2017-12-07 12:06 UTC, Subhash-Saurabh commented
@gxyd I have only modified the code for latex part . I am currently working on the pprint bug and I will commit as soon as possible.

2017-12-07 14:59 UTC, Subhash-Saurabh commented
@gxyd For the pprint part should I submit a new PR or make additional commits in this PR ?

2017-12-07 15:04 UTC, gxyd commented
It will be preferable if you fix that in this PR. Since, I think it is related to making the same expression work for different printings.

2017-12-08 11:53 UTC, Subhash-Saurabh commented
@gxyd I have added the fix for pprint part also. Can you please review it and suggest if any changes are to be made.

2017-12-09 05:30 UTC, gxyd reviewed
instead of `collect_const` use `Mul(-1, ..., evaluate=False)`, I believe that will be a more direct test. See this comment of Aaron https://github.com/sympy/sympy/issues/13651#issuecomment-349149751

Apart from these comments, this PR looks good to me.

2017-12-09 05:30 UTC, gxyd commented on sympy/printing/pretty/pretty.py
> +            if pform.binding > prettyForm.NEG or pform.binding == prettyForm.ADD:
Can you break this line using `( )` brackets around the complete line, so that line length is less than 79 characters?

2017-12-09 05:30 UTC, gxyd commented on sympy/printing/pretty/tests/test_pretty.py
> +    Complement, Interval, Intersection, Union, EulerGamma, GoldenRatio, collect_const)
put `collect_const` on the next line.

2017-12-09 05:30 UTC, gxyd commented on sympy/printing/pretty/tests/test_pretty.py
> +    expr = c + collect_const(-a - b)
`expr` -> `expr1`.

2017-12-09 05:30 UTC, gxyd commented on sympy/printing/pretty/tests/test_pretty.py
> +    expr = c + collect_const(-a + b - d)
`expr` -> `expr2`.

2017-12-09 05:30 UTC, gxyd commented on sympy/printing/pretty/tests/test_pretty.py
> +    expr = c + collect_const(-a - b)
instead have `expr1 = c + Mul(-1, a + b, evaluate=False)` not `collect_const`.

2017-12-09 05:30 UTC, gxyd commented on sympy/printing/tests/test_latex.py
> +    expr = c + collect_const(-a - b)
use `Mul(-1, a + b, evaluate=...)` just like above comment.

2017-12-09 05:31 UTC, gxyd commented on sympy/printing/pretty/tests/test_pretty.py
> +    expr = c + collect_const(-a + b - d)
Also use `Mul` here as well.

2017-12-09 06:37 UTC, gxyd approved these changes
LGTM for merging, once tests pass.

2017-12-10 02:59 UTC, gxyd commented
Thanks for your contribution. Good work.

2017-12-10 02:59 UTC, merged

2017-12-10 03:04 UTC, gxyd commented
Also make sure you use 'Fixes #NNNN' in one of your commits, *not* just #NNNN. This way the issue will be automatically closed.