Get the vector from one point to another expressible in a single reference frame
sympy/sympy pull request #13736
Opened 2017-12-12 20:32 UTC by shattar

Added the ability to get the vector from one point to another that is represented, or representable, in a single reference frame.

#### References to other Issues or PRs

#### Brief description of what is fixed or changed
Added options to the pos_from method of the Point class in order to specify that the resultant vector should be expressible in the given reference frame, or any reference frame at all.

This is needed because the pos_from method was previously creating a vector along the shortest number of connected points, even if there was no orientation specified between the reference frames through which those relative point locations were defined.  The new options will allow the selection of the smallest chain of connected points whose resultant vector is expressible in a single frame.

#### Other comments
A new method was added to the Vector class called `check_expressable` in order avoid having to go through the entire dcm transformation of the vector just to find out if the connection exists.

2017-12-12 22:08 UTC, shattar commented
Some tests are failing due to stack overflow during test execution.  This is not something introduced with this pull request.

> sympy/combinatorics/coset_table.py[3] . Fatal Python error: Cannot recover from stack overflow.

2017-12-12 22:56 UTC, moorepants commented
I have to get through grading this week and can have a look come the weekend or next week. Thanks for the addition! Seems like a good idea.

2017-12-12 23:13 UTC, asmeurer commented
I opened https://github.com/sympy/sympy/issues/13737 for the test failure. It's probably intermittent, meaning it will likely go away once you push another commit.

2017-12-14 10:11 UTC, ylemkimon commented
Please rebase on sympy/master. Thank you!

2018-10-07 12:06 UTC, moorepants requested changes
I don't quite understand what this is doing? If you create a new position with `locatenew()`, why doesn't `pos_from()` just return that vector?

2018-10-07 12:06 UTC, moorepants commented on sympy/physics/vector/point.py
> +            Expresses the resulting vector in this frame
Initial reaction is that we should leave this to the `express()` method on `Vector`. Why is it necessary to have this here?

2018-10-07 12:06 UTC, moorepants commented on sympy/physics/vector/tests/test_point.py
> +    assert P.pos_from(O, frame=B) == 10 * N.x + 5 * B.x
Why is `P.pos_from(O).express(N)` not possible?

2018-10-07 12:06 UTC, moorepants commented on sympy/physics/vector/tests/test_point.py
> +    assert P.pos_from(O, frame=B) == 10 * N.x + 5 * B.x
Also, why would there be B unit vectors if you set `frame=N)?

2018-10-07 12:06 UTC, moorepants commented
Needs release notes as per: https://github.com/sympy/sympy/wiki/Writing-Release-Notes

2019-09-21 06:56 UTC, czgdp1807 commented
@moorepants I have updated the release notes entry. Please take a look at this PR.

2019-09-21 16:39 UTC, moorepants commented
I raised several issues two years ago about this, specifically regarding it be a redundancy that `express()` already handles fine. As it stands I do not support merging this.

2019-09-21 19:21 UTC, czgdp1807 commented
So probably we should close this PR.

2020-03-20 17:45 UTC, czgdp1807 commented
Closing this PR for now as the reviews are not supportive of merging. However, please let us know if there is a need to re-open this. Thanks for your contributions.

2020-03-20 17:45 UTC, closed without merging