@/__matmul__ now only performs matrix multiplication
sympy/sympy pull request #13773
Opened 2017-12-19 10:44 UTC by abhigyank

Add check to allow __matmul__ to perform only matrix multiplication and throws ValueError if
scalars are used as operators or operands.

#### References to other Issues or PRs

This PR will fix #13766 .

#### Brief description of what is fixed or changed
```
>>> B = Matrix([[2, 3], [1, 2]])
>>> 2@B
```
and
```
>>> B@2
```
now throws ValueError: Scalar operands are not allowed, use '*' instead

2017-12-19 11:26 UTC, abhigyank commented
@asmeurer Have a look at it.

2017-12-19 18:47 UTC, asmeurer commented on sympy/matrices/common.py
> +            return
Remove the `return`.

2017-12-19 18:47 UTC, asmeurer commented on sympy/matrices/common.py
> +            raise ValueError("Scalar operands are not allowed, use '*' instead");
Don't put semicolons at the end of lines.

2017-12-19 18:48 UTC, asmeurer commented
There are two PRs fixing this, this one and https://github.com/sympy/sympy/pull/13772.

2017-12-19 18:48 UTC, asmeurer commented on sympy/matrices/tests/test_commonmatrix.py
> +    raises(ValueError, lambda: 2@a)
You will need to use eval for this test, and make it so that it skips in Python versions less than 3.5.

2017-12-19 18:49 UTC, asmeurer commented on sympy/matrices/tests/test_commonmatrix.py
> +    raises(ValueError, lambda: 2@a)
Or you can just test `__matmul__`.

2017-12-19 18:50 UTC, asmeurer commented
Both PRs implement the fix in the same way, and both have some minor issues. @abhigyank, 	Subhash-Saurabh, how would you like to proceed here?

2017-12-19 19:53 UTC, Mohit17067 commented
I have no right to do anything here but there was a third person also who said before these two guys that he is going to work on this issue ( issue #13766 ). I think you guys should give him a chance also else it will be difficult for newcomers to solve issues. No offense to the two who solved it. The decision is all yours.

2017-12-19 20:48 UTC, gxyd commented
I think @ArighnaIITG is already working on a few PR's. BTW there are few other issues that might need your love, for ex. https://github.com/sympy/sympy/issues/11345 is also based on matrices and is easy to fix, one of you can try that.

2017-12-20 02:49 UTC, abhigyank commented
This is my first issue at such a big project and wasn't aware of other PRs. Its upto you to accept any PR. No issues there. 
@asmeurer 
I have pushed a commit making your recommended changes. Please look at it.

2017-12-20 04:44 UTC, Subhash-Saurabh commented
@abhigyank You can continue with the work. In the mean time I will work on some other issues .

2017-12-20 08:41 UTC, asmeurer commented
https://github.com/sympy/sympy/pull/13772#issuecomment-352860133 makes a good point. We should probably return NotImplemented instead of raising ValueError. It will give a less informative error message, but it will allow other objects to define `__matmul__` behavior on SymPy matrices easier.

2017-12-20 08:48 UTC, abhigyank commented
I think NotImplemented error isn't appropriate as we actually had that implemented already, and now are removing that functionality since ```__matmul__``` should work for scaler operands. Raising a TypeError is still ok, but is on similar lines with ValueError.

2017-12-20 09:15 UTC, asmeurer commented
`NotImplemented` is not the same as `NotImplementedError`. See https://docs.python.org/3/library/constants.html#NotImplemented

2017-12-20 09:28 UTC, abhigyank commented
Okay, I understand. It seems appropriate in this case then. Do you want me to implement it?On Dec 20, 2017 2:45 PM, Aaron Meurer <notifications@github.com> wrote:NotImplemented is not the same as NotImplementedError. See https://docs.python.org/3/library/constants.html#NotImplemented

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

2017-12-20 23:04 UTC, asmeurer commented
Yes

2017-12-21 04:36 UTC, abhigyank commented
@asmeurer Have a look now.

2017-12-22 03:35 UTC, abhigyank commented
I don't understand from the logs why the Travis build failed. What's the issue?

2017-12-22 04:13 UTC, abhigyank commented
I think it can be merged @asmeurer

2017-12-23 21:34 UTC, asmeurer commented
Add a test for `a @ 2`/`a.__rmatmul__(2)` as well.

2017-12-23 21:35 UTC, asmeurer commented on sympy/matrices/tests/test_commonmatrix.py
> +        eval('2 @ a')
Add a comment here that this is done this way because @ is only supported in Python 3.5+.

2017-12-25 04:39 UTC, abhigyank commented
@asmeurer I have done and pushed. Have and look and merge maybe.

2017-12-25 12:28 UTC, ylemkimon commented
I think a check for `len(shape) == 2` is needed.

2017-12-25 17:51 UTC, abhigyank commented
That check is already present in __mul__ .

2017-12-26 02:38 UTC, ylemkimon commented
But if `len(shape) != 2`, it will perform a scalar multiplication.

2017-12-26 04:16 UTC, abhigyank commented
@ylemkimon in line 1976 ```other = _matrixify(other)``` , this passes the other through _matrixify() function, which already contains check for ```is_Matrix``` and ```len(shape)==2``` and then returns other accordingly. So what we receive has already passed through the given conditions and hence we can only check for its matrix feature. The other checks are redundant and not required again.

2017-12-26 05:01 UTC, ylemkimon commented
https://github.com/sympy/sympy/blob/7d0231704a21c5dbe4740e1f354f736b5a313acc/sympy/matrices/common.py#L2265-L2274 In `_matrixify`, if `len(shape) != 2`, it will return original object(`other`) unchanged. And since it has `shape` attribute, it will be passed to `__mul__`. In `__mul__`, if not `is_Matrix` and not `is_MatrixLike`, i.e., `len(shape) != 2`, it will be passed to `_eval_scalar_mul`, which is a scalar multiplication.

2017-12-26 05:19 UTC, abhigyank commented
@ylemkimon Okay, I get your point. So ``` if (getattr(mat, 'is_Matrix', False) and getattr(mat, 'is_Matrix', False)): return NotImplemented ``` should fix this right?

2017-12-26 05:37 UTC, ylemkimon commented
Yes, but you seems to have missed `not`. So, it will be look like:
```python
other = _matrixify(other)
if not getattr(other, 'is_Matrix', False) or not getattr(other, 'is_Matrix', False)):
    return NotImplemented
```

2017-12-26 06:22 UTC, abhigyank commented
@ylemkimon  @asmeurer  Have a look now, and merge if ready.

2017-12-26 15:51 UTC, ylemkimon requested changes
Otherwise LGTM

2017-12-26 15:51 UTC, ylemkimon commented on sympy/matrices/common.py
> +            return NotImplemented
`shape` attribute check is no longer needed.

2017-12-26 16:17 UTC, abhigyank commented
@ylemkimon Amended the previous commit to do your requested changes. Have a look now @ylemkimon  @asmeurer

2017-12-27 02:56 UTC, ylemkimon approved these changes

2017-12-27 02:57 UTC, merged

2017-12-27 02:57 UTC, ylemkimon commented
Thank you for your contribution!