Fix issue 13936: Link Geometry class names to their descriptors.
sympy/sympy pull request #13940
Opened 2018-01-16 14:48 UTC by CedricTravelletti

Fixes #13936 . 

Added link to the descriptors of the Geometry classes in the documentation of the Geometry module.

2018-01-17 10:14 UTC, ylemkimon commented
Restarted failed/canceled builds.

2018-01-19 19:38 UTC, gxyd commented
Can you also fix the `Contains` issue mentioned in the issue?

You'll need to change `automodule` to `module` (remove `:members:`) and add `autoclass` (with `:members`)

2018-01-20 10:41 UTC, CedricTravelletti commented
Sure, I'll start now.

2018-01-20 19:15 UTC, gxyd approved these changes

2018-01-20 21:29 UTC, gxyd commented on doc/src/modules/geometry/index.rst
> +* :class:`~sympy.geometry.line.Segment`, :class:`~sympy.geometry.line.Ray`, :class:`~sympy.geometry.line.Segment`
Wait a minute, the first one has to be `Line`, not `Segment`.

I missed that in the first view. Otherwise LGTM.

2018-01-21 17:24 UTC, gxyd requested changes

2018-01-21 17:24 UTC, gxyd commented on doc/src/modules/geometry/index.rst
> +* :class:`~sympy.geometry.line.Segment`, :class:`~sympy.geometry.line.Ray`, :class:`~sympy.geometry.line.Segment`
The first one needs to be `Line` not `Segment`.

2018-01-22 14:08 UTC, CedricTravelletti commented
Changes implemented, Line is now referenced.

2018-01-22 14:38 UTC, ylemkimon commented on doc/src/modules/geometry/index.rst
> +* :class:`~sympy.geometry.line.Line`, :class:`~sympy.geometry.line.Segment`, :class:`~sympy.geometry.line.Ray`, :class:`~sympy.geometry.line.Segment`
`Segment` occurs twice.

2018-01-22 19:14 UTC, CedricTravelletti commented
Sorry about that, my bad. It is fixed now.

2018-01-23 06:43 UTC, merged

2018-01-23 06:43 UTC, ylemkimon commented
Thank you!