Add functionality for infinity norm of matrices
sympy/sympy pull request #13986
Opened 2018-01-21 19:19 UTC by RavicharanN

#### References to other Issues or PRs
With reference to issue #13985

#### Brief description of what is fixed or changed
Functionalities for infinity/NegativeInfinity norms have been added.

#### Other comments

2018-01-21 19:47 UTC, normalhuman requested changes
The docstring of norm method should be edited to reflect the existence of inf-norm.

A test needs to be added too. 

The proposed addition of "-inf norm" needs some justification: what other CAS implement this norm, and how? Unlike positive-order norms, the negative orders lack universally accepted mathematical interpretation.

Also, please edit the PR text according to Wiki page [Writing pull request title and description](https://github.com/sympy/sympy/wiki/Development-workflow#writing-pull-request-title-and-description)

2018-01-21 19:47 UTC, normalhuman commented on sympy/matrices/matrices.py
> +            elif ord == S.NegativeInfinity: # Negative Infinity Norm - Maximum column sum
The "negative infinity norm" or matrices would not be maximum column sum. The maximum column sum is 1-norm, already implemented above.

If we want to introduce -oo norm for matrices, that merits a separate discussion. For example, [Matlab docs](https://www.mathworks.com/help/symbolic/norm.html?s_tid=gn_loc_drop) do not define it. 

Generally, one may think  that the order -p norm for matrices should be min||Ax||_p over ||x||_p = 1 (this is how it works for p=2 currently) but this is just one interpretation.

2018-01-21 20:24 UTC, RavicharanN commented
Sure, I'll make the changes

2018-01-21 22:42 UTC, RavicharanN commented
@normalhuman Can you please review it now?

2018-01-21 22:53 UTC, normalhuman commented
The table of norms in the docstring of the method should have an entry for oo norm: see the line 3381.

2018-01-22 05:39 UTC, RavicharanN commented
PR updated

2018-01-22 06:14 UTC, normalhuman approved these changes
Looks good. 

In the future, please follow the [Developer Workflow](https://github.com/sympy/sympy/wiki/Development-workflow), in particular: (1) create a branch for each feature (instead of committing to master), (2) follow GitHub rules for automatic closing of issues by writing "Fixes #NNNNN" or "Closed #NNNNN" in the text of a pull request.

2018-01-22 19:39 UTC, merged