made the code simpler
sympy/sympy pull request #14011
Opened 2018-01-25 18:34 UTC by RISHAV98

#### References to other Issues or PRs

#### Brief description of what is fixed or changed

#### Other comments

2018-01-25 22:44 UTC, normalhuman requested changes
Please follow the [development workflow](https://github.com/sympy/sympy/wiki/Development-workflow), in particular regarding pull request description, title, and creating a branch for each pull request. 

And testing. This line throws the error `TypeError: 'Symbol' object is not iterable`.

2018-01-26 05:16 UTC, ylemkimon commented on examples/beginner/basic.py
> +    a,b,c = Symbol('a b c')
`Symbol` returns single symbol, whereas `symbols` return multiple symbols if given.

2018-01-26 07:14 UTC, RISHAV98 commented
symbols module  cannot be import from sympy.

2018-01-31 14:57 UTC, smichr commented
> symbols module cannot be import from sympy.

If you do a search for `import symbols` you will see how this is imported successfully.

2018-02-14 06:32 UTC, RISHAV98 commented
a,b,c = symbols('a b c')

2018-02-15 07:23 UTC, RISHAV98 commented
have a look on this

2018-02-16 10:09 UTC, closed without merging