Zeta printing in octave
sympy/sympy pull request #14962
Opened 2018-07-23 20:59 UTC by ethankward

Two method zeta function is not equivalent to SymPy's. Fixes #14820.

2018-07-23 23:35 UTC, asmeurer commented
This needs a release notes entry. See https://github.com/sympy/sympy/wiki/Writing-Release-Notes

2018-07-24 02:01 UTC, cbm755 commented
I had already done this as part of #14821 but I'm more than happy to take your version.

May I suggest we trade reviews?  I'll review this and you review mine.

2018-07-24 02:06 UTC, cbm755 requested changes

2018-07-24 02:06 UTC, cbm755 commented on sympy/printing/tests/test_octave.py
> +    n = Symbol('n')
I think x is imported at the top

2018-07-24 02:06 UTC, cbm755 commented on sympy/printing/tests/test_octave.py
> +    # test cases for issue #14820
can we just call the fcn `test_zeta_printing_14820():` and don't have the comment

2018-07-24 02:07 UTC, cbm755 commented on sympy/printing/tests/test_octave.py
> +    # test cases for issue #14820
or maybe its `...printing_issue_14820`, look through other issues to see which is more standard.

2018-07-24 02:09 UTC, cbm755 commented
This looks almost good to go!  Mostly minor, except maybe the `self._print`: IIRC this matters if `x` is not just a simple but something that itself needs to be `print`ed.

2018-07-24 04:30 UTC, ethankward commented
Thanks for your comments- sorry I didn't realize you had already requested this change. I'll close this as your pull request came first and is more comprehensive.

2018-08-05 05:10 UTC, cbm755 commented on sympy/printing/tests/test_octave.py
> +
Thanks for the changes.  Just need to remove this blank line and I will merge.

2018-08-06 04:43 UTC, cbm755 commented
I changed your release notes entry from "printing" to "codegen".

This looks good, will merge.

2018-08-06 04:44 UTC, merged