Autolev Parser Documentation 2
sympy/sympy pull request #15066
Opened 2018-08-09 20:57 UTC by NikhilPappu

- other
  - Added the Gotchas section in autolev_parser.rst in the mechanics part of the documentation.

2018-08-09 20:58 UTC, NikhilPappu commented
@moorepants

2018-08-09 22:25 UTC, moorepants commented
Merge in master, since we've merged the first PR.

2018-08-10 05:39 UTC, NikhilPappu commented
@moorepants This PR is from autolev_parser_docs_2 to master. The first PR didn't get merged so can you please do that?

2018-08-10 14:29 UTC, moorepants commented
Oh, I thought I merged it!

2018-08-10 14:30 UTC, moorepants commented
Ok, it is merged.

2018-08-10 14:59 UTC, NikhilPappu commented
@moorepants Can you now review this PR and the 3rd one #15067 ? Also please take a look at #15013 and #15006 .

2018-08-10 19:52 UTC, moorepants commented
Yes, I'll get to them as I have time. I'm aware of all your PRs.

2018-08-13 19:41 UTC, Abdullahjavednesar commented on doc/src/modules/physics/mechanics/autolev_parser.rst
> +  especially the case for eigenvalues and eigenvetors.
eigenvetors -> eigenvectors

2018-08-13 19:45 UTC, Abdullahjavednesar commented on doc/src/modules/physics/mechanics/autolev_parser.rst
> +  all occurences of it in the Kane's equations. For example have a look at
occurences -> occurrences

2018-08-13 22:08 UTC, NikhilPappu commented
@certik 
Travis seems to have some issues. The build passed before but isn't passing now after just fixing typos.

2018-08-13 22:10 UTC, certik commented
I restarted the failed builds.

2018-08-18 17:01 UTC, moorepants requested changes
This a very helpful document and clearly explained. Nice work. I've left some feedback that I'd like addressed before merging.

2018-08-18 17:17 UTC, NikhilPappu commented on doc/src/modules/physics/mechanics/autolev_parser.rst
> +------------------------------------------------------------------------
It seems to be valid restructuredText. These lines render well and separate the different sections nicely.

2018-08-18 18:41 UTC, NikhilPappu commented on doc/src/modules/physics/mechanics/autolev_parser.rst
> +  change ``me.dynamicsymbols._t`` to ``me.dynamicsymbols('t')`` in this case.
The main problem is that if Autolev finds the variable `T` in an equation it substitutes the time instance for it during numerical substitution.
In PyDy, we have to explicitly pass in specifieds in the System class and only these specifieds are substituted for with time instances.
This problem can be fixed if PyDy's System class can substitute the time instances for occurences of dynamicsymbols._t.

2018-08-21 05:40 UTC, moorepants approved these changes

2018-08-21 05:40 UTC, merged