PyDy for Autolev Users guide
sympy/sympy pull request #15077
Opened 2018-08-11 16:30 UTC by NikhilPappu

- other
  -  Added a guide pydy_for_autolev_users.rst in the mechanics part of the documentation.

2018-08-11 19:55 UTC, Abdullahjavednesar commented on doc/src/modules/physics/mechanics/autolev_parser.rst
> +  to specifiy the frame as SymPy needs this information to compute the
specifiy -> specify

2018-08-11 20:03 UTC, Abdullahjavednesar commented on doc/src/modules/physics/mechanics/pydy_for_autolev_users.rst
> +| Fortan code from a small set of   | C or Octave/Matlab code from a    |
Fortan -> Fortran

2018-08-11 20:09 UTC, Abdullahjavednesar commented on doc/src/modules/physics/mechanics/pydy_for_autolev_users.rst
> +Dcumentation <http://docs.sympy.org/latest/modules/physics/vector/index.html>`_
Dcumentation -> Documentation

2018-08-13 22:31 UTC, NikhilPappu commented
Sorry about the small commit names. I have just merged stuff from other branches or tried to make changes so the Travis tests pass.

2018-08-16 21:02 UTC, asmeurer commented
If this document is about PyDy specifically shouldn't it go in the PyDy documentation rather than the SymPy documentation?

2018-08-16 21:02 UTC, asmeurer commented
CC @moorepants

2018-08-17 04:04 UTC, NikhilPappu commented
Aaron,
We have decided that it would be best to have this in SymPy as the parser
is here. The guide mostly talks about SymPy vs Autolev code and just
touches on PyDy. I have used the name "PyDy" in the title as it is broader
and encompasses the SymPy mechanics module. I could change the name if
required.

On Fri 17 Aug, 2018, 2:32 AM Aaron Meurer, <notifications@github.com> wrote:

> CC @moorepants <https://github.com/moorepants>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sympy/sympy/pull/15077#issuecomment-413683822>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFGWJy0w35W6z79EgwGiNrauTse12h7hks5uRd3vgaJpZM4V5OdH>
> .
>

2018-08-18 17:02 UTC, moorepants commented
@asmeurer I think we can just rename it something like "SymPy Mechanics for Autolev Users". It belongs here for now. The vast majority of the code it is referencing is in SymPy.

2018-08-18 17:06 UTC, moorepants requested changes
This looks graat. Please address the comments on changing the language to reflect "SymPy Mechanics" instead of PyDy for everything above the numerical code section and this can be merged.

2018-08-18 17:06 UTC, moorepants commented on doc/src/modules/physics/mechanics/pydy_for_autolev_users.rst
> +PyDy for Autolev Users
Change to ``SymPy Mechanics for Autolev Users``.

2018-08-18 17:06 UTC, moorepants commented on doc/src/modules/physics/mechanics/pydy_for_autolev_users.rst
> +It would be nice to have a basic understanding of SymPy and PyDy before
Orient references to PyDy to "SymPy Mechanics".

2018-08-18 17:06 UTC, moorepants commented on doc/src/modules/physics/mechanics/pydy_for_autolev_users.rst
> +----------------------------------------
You can mention PyDy (instead of SymPy Mechanics) in this section.

2018-08-21 05:39 UTC, moorepants approved these changes

2018-08-21 05:41 UTC, merged