Substituted kindiffdicts in forcing_full of kane.py
sympy/sympy pull request #15173
Opened 2018-08-30 17:17 UTC by NikhilPappu

Refer to [this](https://gitlab.com/sympy/autolev-test-examples/blob/master/autolev-tutorial/tutor6.py) file in the GitLab repo. The numerical PyDy integration parts weren't working initially here but they work after this change so I added this as it wasn't breaking the existing tests. I am not exactly sure of the reason though as the eoms don't seem to change.

- physics/mechanics
  - Added xreplace kindiffdict substitutions in the `forcing_full()` method of `kane.py`.

2018-08-30 18:28 UTC, moorepants commented
Related symengine issue: https://github.com/symengine/symengine/issues/1456

2018-08-30 18:35 UTC, NikhilPappu commented on sympy/physics/mechanics/kane.py
> +        return -Matrix([f1.subs(self.kindiffdict()), self._f_d.subs(self.kindiffdict()), self._f_dnh.subs(self.kindiffdict())])
How would you check for SymEngine? Is it fine to add a try except block as that is the only case where it fails?

2018-08-30 19:58 UTC, moorepants commented on sympy/physics/mechanics/kane.py
> +        return -Matrix([f1.subs(self.kindiffdict()), self._f_d.subs(self.kindiffdict()), self._f_dnh.subs(self.kindiffdict())])
In `external` there is an `import_module` function that gracefully handles import errors. You can do:

```python
symengine = import_module('symengine')

if symengine:
```

2018-08-30 21:06 UTC, moorepants commented
`kindiffdict()` returns a dictionary mapping the derivatives of the coordinates to expressions involving the coordinates and defined speeds. For the standard workflow, as soon as you have these defined you'd like to replace any instance of a q' in velocity vectors with these expressions. So this substitution would ideally come at the velocity and acceleration vector formation stages, i.e. before forming Fr+Fr*.

You can also form Fr+Fr* and then substitute these and their derivatives in. But I think you'd have both q' and q'' that need to be replaced. You are substituting them in every time that the form Mu' = F is needed, where Mu'-F = Fr+Fr*. I think this means that in a typical problem you may be doing this substitution more than once. There is only reason to do it once.

Lastly, you may not want these automatically substituted because it just makes the equations more complex. cse() can undo this complexity but it may not be worth it. I think the default should be to substitute (at some point) but that you should allow this to be turned off in an option in KanesMethod().

The equations could be like:

q' = g(q, u, t)
q'' = g_p(q, q', u, u', t)
Fr* = h(q, q', q'', u, u', t) 
Fr = f(q, q', u, t)

and that's probably ok.

Sometimes the kin diff equations can be super complicate and long expressions. It doesn't always make sense to substitute them at all.

2018-08-31 04:07 UTC, NikhilPappu commented
@moorepants I am doing this here because I am using the System class in my PyDy integration code which does not allow me to modify the eoms. Should I use generate_ode_function() instead or should I just make this change with an option?

2018-08-31 05:02 UTC, NikhilPappu commented
@moorepants Ideally, I really think the System class should accept the eoms instead of the kanes method object. This makes it far more flexible. Should I open an issue for this?

2018-08-31 05:27 UTC, moorepants commented
> Should I use generate_ode_function() instead or should I just make this change with an option?

Let's try to stick with `System`. Make this substitution an option when calling `.kanes_equations(sub_kin_diffs=True)` and make it True by default. This leaves the option open to not do this if needed.

> Ideally, I really think the System class should accept the eoms instead of the kanes method object.

We created https://github.com/sympy/sympy/blob/master/sympy/physics/mechanics/system.py to let users construct custom sets of symbolic equations to pass into pydy.System.

2018-08-31 11:25 UTC, NikhilPappu commented
@moorepants

2018-08-31 13:58 UTC, moorepants requested changes
Needs a unit test.

2018-08-31 13:58 UTC, moorepants commented on sympy/physics/mechanics/kane.py
> +            self.sub_kin_diffs = True
Can't this just be: `self.sub_kin_diffs = sub_kin_diffs`? I also recommend making the attribute private (`self._sub_kin_diffs`).

2018-08-31 13:58 UTC, moorepants commented on sympy/physics/mechanics/kane.py
> +    def kanes_equations(self, bodies, loads=None, sub_kin_diffs=True):
Add a docstring explaining what the kwarg does.

2019-09-11 17:00 UTC, czgdp1807 commented
@NikhilPappu Are you still working on this? Please resolve the conflicts and make the requested changes. Thanks.

2023-03-11 06:49 UTC, moorepants commented
#24890 likely solves this.

2023-03-11 06:49 UTC, closed without merging