Added heuristics kwarg for Limit.doit solving big-oh notation error, added tests
sympy/sympy pull request #15512
Opened 2018-11-19 14:40 UTC by avishrivastava11

Added heuristics `kwarg` for `limit.doit` solving big-oh notation error, added tests

Fixes #9917

#### Release Notes

* series
   * Added heuristics `kwarg` for `limit.doit`
   * Added tests

2018-11-24 20:11 UTC, normalhuman requested changes

2018-11-24 20:11 UTC, normalhuman commented on sympy/series/tests/test_order.py
> +    assert O(n*sin(n) + 1, (n, oo)) == O(n*sin(n) + 1, (n, oo))
This line, as well as some of the following, do not actually test the behavior of Order. Same object on both sides of equality, so equality is assured to hold regardless of what that object is. So it holds in current master branch as well. 

Perhaps you meant to test 
```
O(n*sin(n)+1, (n, oo)).expr == n*sin(n) + 1
```
which would indeed verify that the expression returned by Order constructor is what you expect.

2019-01-28 03:03 UTC, avishrivastava11 commented
@oscarbenjamin 
>Are you still working on this?

Forgive me, I was a bit preoccupied with some work. I'm getting onto it.

2019-01-28 03:18 UTC, oscarbenjamin commented
There's no need to be forgiven :). We all have other things to do as well!

I was just asking so it would be clear to anyone else thinking about working on this.

2022-02-09 17:03 UTC, praneethratna commented
This PR can be closed now since issue #9917 has been fixed and tests for it are added in #22373.

2022-05-07 03:49 UTC, closed without merging