Added shear stress and axial force fucntions in continuum physics
sympy/sympy pull request #16384
Opened 2019-03-22 12:18 UTC by abhinavsagar

#### References to other Issues or PRs

[Fixes #16366 ](https://github.com/sympy/sympy/issues/16366)

#### Brief description of what is fixed or changed
Added shear stress and axial force fucntions in continuum physics .

#### Other comments

#### Release Notes

* functions
  * added fucntion for calculating shear stress.
  * added fucntion for calculating axial stress.

2019-03-22 14:06 UTC, divyanshu132 requested changes

2019-03-22 14:28 UTC, abhinavsagar commented on sympy/physics/continuum_mechanics/beam.py
> +        return integrate(self.axial_force, x)
@divyanshu132 I think there are already no trailing whitespaces. If there is can you show me where they are

2019-03-22 14:50 UTC, divyanshu132 commented on sympy/physics/continuum_mechanics/beam.py
> +        return integrate(self.axial_force, x)
Have a look at travis log.
`AssertionError: File contains trailing whitespace: /home/travis/build/sympy/sympy/sympy/physics/continuum_mechanics/beam.py, line 851.`

2019-03-22 17:15 UTC, abhinavsagar commented on sympy/physics/continuum_mechanics/beam.py
> +        return integrate(self.axial_force, x)
@divyanshu132 I am still not getting it. I know travis log is showing but if it was whitespaces problem it should be at line 783 and line 817 also right?

2019-03-23 01:20 UTC, divyanshu132 commented on sympy/physics/continuum_mechanics/beam.py
> +        return integrate(self.axial_force, x)
Its not like that, I would suggest to use rich text editors like Sublime or something else where you can easily get rid of these whitespaces.

2019-03-23 03:16 UTC, abhinavsagar commented on sympy/physics/continuum_mechanics/beam.py
> +        return integrate(self.axial_force, x)
Ok thanks for the help

2019-03-24 04:55 UTC, closed without merging