implemented methods for ODEs to solve in terms of bessel and Airy's  …
sympy/sympy pull request #16540
Opened 2019-04-02 14:14 UTC by RituRajSingh878

Currently, sympy does not support the ODEs solution in term of Bessel function.
So for this, I have taken help from pr #10870 and Implemented  ODEs in term of Bessel and Airy's function.

```
Eq(x ** 2*Derivative(y(x),x,x)-(ax+b)*y(x))
The above equation now has solution c1*Ai(x)+x2*Bi(x)
where Ai(x) and Bi(x) are Airy's functions of first and second kind respectively

```
```
Eq(x**2*f(x).diff(x,2)+x*f(x).diff(x)+(x**2-a**2)*f(x),0)
The above equation now has solution 
                 ⎛   ____   ⎞             ⎛   ____   ⎞
                 ⎜  ╱  2    ⎟             ⎜  ╱  2    ⎟
f(x) = C₁⋅besselj⎝╲╱  a  , x⎠ + C₂⋅bessely⎝╲╱  a  , x⎠

where besselj(n,x) and bessely(n,x) are Bessel's functions of first and second kind respectively
```

2019-04-02 16:26 UTC, oscarbenjamin commented
Can you base this on the commits from #10870?

You can squash them to a single commit but make sure it still records the same author. Then commit your changes on top.

2019-04-03 13:25 UTC, supreet11agrawal requested changes

2019-04-03 13:25 UTC, supreet11agrawal commented on sympy/solvers/tests/test_ode.py
> +    assert dsolve(eq) == Eq(f(x), C1*besselj(1/3, 9*x) + C2*bessely(1/3, 9*x))
Perhaps, you should Simpify these terms. Eg. `S(1)/3`.
Python2.7 sometimes gives an error if not simpified

2019-04-03 14:14 UTC, RituRajSingh878 commented
> Can you base this on the commits from #10870?
> 
> You can squash them to a single commit but make sure it still records the same author. Then commit your changes on top.

Sure

2019-04-03 14:14 UTC, RituRajSingh878 commented
> Can you base this on the commits from #10870?
> 
> You can squash them to a single commit but make sure it still records the same author. Then commit your changes on top.

okkk

2019-04-03 22:40 UTC, oscarbenjamin commented on sympy/solvers/ode.py
> -    "order_reducible",
Looks like you've accidentally removed the order_reducible method...

2019-04-03 22:40 UTC, oscarbenjamin commented on sympy/solvers/ode.py
> -
Please restore this blank line

2019-04-03 22:41 UTC, oscarbenjamin commented on sympy/solvers/ode.py
> -            matching_hints['nth_algebraic_Integral'] = r
Here also you've removed order_reducible accidentally.

2019-04-03 22:53 UTC, oscarbenjamin commented
I think that the way you based this PR on #10870 wasn't quite right.

I think it is probably better to do this on a new branch (needing a new PR).

1. Add the original authors repo as a remote (`git remote add`) and fetch their branches (`git fetch`)
2. Checkout the branch `git checkout remotename/branchname` where this work was done. Then checkout a branch (`git checkout -b newname`) from there. Push that branch up to your fork (`git push -u origin newname`).
3. At this point you have your own branch with their commits in so you can delete the remote you added (`git remote rm`).
4. Now apply your work onto the code, commit and push.
5. Open a new PR. Make a comment here referring to the new PR and vice-versa.
6. Close this PR.

As you become more proficient some of these steps could be streamlined with `git diff` and `git apply`.

2019-04-07 11:21 UTC, RituRajSingh878 commented
I have made another pr #16581 .

2019-04-07 11:22 UTC, closed without merging