Lineintegral
sympy/sympy pull request #16558
Opened 2019-04-05 08:40 UTC by abhinav28071999

* Vector
  *  Added line integral in vector module

2019-04-05 08:59 UTC, friyaz requested changes
There are spelling mistakes.
feild -> field
staarting ->starting.

2019-04-05 09:02 UTC, friyaz reviewed
I think the API can be improved.
Instead of passing parametric equation of curve, we should make a class to represent curve and then pass object of this class to `LineIntegrate`.

Even if we go with this API, user should be able to pass parametric equation of line as a tuple rather than a single term.

2019-04-05 09:13 UTC, friyaz reviewed
This implementation requires field to be vector field. It does not work for scalar field.

2019-04-05 09:46 UTC, jksuom commented
There is `line_integrate` in `integrals`. There should preferably be only one function for all line integrals.

2019-04-05 10:13 UTC, abhinav28071999 commented
@jksuom  Hey, i saw the idea of vector integration on the ideas page of Gsoc. So i was hoping to 
make a patch regarding that. It was given to implement line integral , surface integral and volume integral. So i thought to start line integration. Please tell me what are the thing required in the vector integration idea page.

2019-04-05 11:44 UTC, jksuom commented
The vector integration idea has been discussed several times on the mailing list, for instance, https://groups.google.com/forum/#!msg/sympy/lBi1VvkYPaQ/isjPRi0fAgAJ and https://groups.google.com/forum/#!msg/sympy/9GFdlK3btwo/BJR390oXBgAJ.

2019-04-07 20:27 UTC, smichr commented on sympy/vector/functions.py
> +def lineintegral(l,field,coord_sys, start,end ):
spaces after commas

2019-04-07 20:29 UTC, smichr commented on sympy/vector/functions.py
> +    Computes line integral.A line integral is an integral where the function
space after period.

remove double period, etc...

newline before Parameters

2019-04-07 20:30 UTC, smichr commented on sympy/vector/functions.py
> +def lineintegral(l,field,coord_sys, start,end ):
Is it possible to infer the coordinate system from the equation given?

2019-11-24 07:08 UTC, czgdp1807 commented
Closing since these comments, https://github.com/sympy/sympy/pull/16558#issuecomment-480245858 and https://github.com/sympy/sympy/pull/16558#issuecomment-480215491 suggest that there is already an existing function satisfying the requirements. Thanks for the contributions. Please let me know if it is needed to be re-opened.

2019-11-24 07:08 UTC, closed without merging