Added aseries function
sympy/sympy pull request #17167
Opened 2019-07-09 13:04 UTC by ArighnaIITG

#### References to other Issues or PRs

#### Brief description of what is fixed or changed

Added asymptotic expansion of series. 
Tests will be added soon.

#### Other comments

**NOTE : ** - This is a work in progress.

#### Release Notes

* series
   * Implemented `aseries` function in `sympy.core.expr` and `sympy.series.aseries`.

2019-07-18 07:57 UTC, ArighnaIITG commented
This PR is almost ready @leosartaj . Open for reviewing.

2019-07-18 08:31 UTC, leosartaj commented
> This PR is almost ready @leosartaj . Open for reviewing.

Can you elaborate what do you mean by almost?

2019-07-18 08:33 UTC, ArighnaIITG commented
Two symbolic tests are not passing, i.e., tests in which there are some symbolic terms. The logic is ready, and all the other tests are passing.

2019-07-28 11:14 UTC, leosartaj commented on sympy/core/expr.py
> +        return (s + o).subs(k, exp(logw))
Add a few comments for key steps.

2019-07-31 06:56 UTC, ArighnaIITG commented
@leosartaj how do I switch the implementation here? How do I call the `aseries` from `core/expr.py`, keeping the logic of the code in `series/aseries.py`?

2019-07-31 09:35 UTC, ArighnaIITG commented
@leosartaj . Comments added. Also, I felt that keeping the same code structure would be better, because if we shift the logic to the `aseries.py` file, that becomes a separate function now. There are a lot of recursive calls which then would have to be changed. It would only create a lot more errors. Also, since `series` and other sub-methods of `series` are maintained in the same exact way, I feel that consistency will also be maintained.

2019-08-01 09:16 UTC, leosartaj commented
Can you give an example where series fails and this works?

2019-08-01 09:18 UTC, leosartaj requested changes

2019-08-01 09:18 UTC, leosartaj commented on sympy/core/expr.py
> +            return s
I am not sure about this. Let's not change the default for now. We can integrate this later. We need to be sure ``aseries`` will cover all the cases which ``series`` covers also maintaining correctness.

2019-08-01 09:18 UTC, leosartaj commented on sympy/core/expr.py
> +        """
I can we make this multi-line comment (using #) rather than docstrings.

2019-08-01 09:18 UTC, leosartaj commented on sympy/core/expr.py
> +        their asymptotic series in terms of their most rapidly varying subexpressions."""
Use # for comments.

2019-08-01 09:18 UTC, leosartaj commented on sympy/core/expr.py
> +                """Recursive step."""
#

2019-08-01 09:18 UTC, leosartaj commented on sympy/series/aseries.py
> +    """
Let's maintain docstring at one place rather than two copies of it.

2019-08-01 09:18 UTC, leosartaj commented on sympy/core/expr.py
> -
Let's keep this line.

2019-08-04 11:40 UTC, ArighnaIITG commented
> Can you give an example where series fails and this works?

The example has been stated in the PR description. All the test cases mentioned in the `tests/test_aseries.py` return only an order term, which is completely wrong. After implementation of this function, they return the asymptotic series.

2019-08-04 18:47 UTC, ArighnaIITG commented
All changes have been integrated @leosartaj .

2019-08-05 14:24 UTC, leosartaj approved these changes

2019-08-05 14:24 UTC, leosartaj commented
LGTM. Will merge in 24hrs if no objection.

2019-08-06 07:13 UTC, merged