change Basic.NaN to S.NaN
sympy/sympy pull request #18100
Opened 2019-12-22 18:09 UTC by namannimmo10

#### References to other Issues or PRs

Fixes #4841

#### Brief description of what is fixed or changed
type object 'Basic' has no attribute 'NaN'.
type object 'Basic' has no attribute 'Zero'

#### Other comments

#### Release Notes

NO ENTRY

2019-12-22 18:18 UTC, ShubhamKJha requested changes

2019-12-22 18:18 UTC, ShubhamKJha commented on doc/src/guide.rst
> +            if isinstance(arg, S.NaN):
```suggestion
            if arg is S.NaN:
```

2019-12-22 18:18 UTC, ShubhamKJha commented on doc/src/guide.rst
> +            if isinstance(arg, S.Zero):
similarly here

2019-12-22 18:22 UTC, namannimmo10 commented on doc/src/guide.rst
> +            if isinstance(arg, S.NaN):
sure. I'll update

2019-12-22 18:58 UTC, sylee957 commented
Can those tutorial be doctestable?

2019-12-22 19:09 UTC, namannimmo10 commented
> Can those tutorial be doctestable?

Explain doctestable?? Maybe extracting the code from docs and testing it??

2019-12-22 19:15 UTC, sylee957 commented
If you change some examples like
```python3
>>> class sign(Function):
...     nargs = 1
...
```
and then it's going to be picked up by our test runner to actually run the code and verify that there is no syntax error or such.

One other advantage by adding some `>>> ` is that you can actually run the piece with the sympy live shell.

If you see some code examples below that can be clickable https://docs.sympy.org/latest/guide.html, you'll know what I mean.

2019-12-22 19:25 UTC, ShubhamKJha approved these changes

2019-12-22 19:35 UTC, namannimmo10 commented
@sylee957 thanks for the tips!

2019-12-22 19:51 UTC, ShubhamKJha commented
You can run `doctest` your changes locally by using
```
python bin\doctest sympy\doc
```
> Can those tutorial be doctestable?

The code can be easily made to be doctested, but the error (here `Basic.NaN` doesn't exist) is not caught because the class is not initialized. Don't know how many such cases would be there.

2019-12-22 19:55 UTC, oscarbenjamin commented
> because the class is not initialized

The example would be better if it was complete with initialisation and usage of the class.

2019-12-23 00:07 UTC, oscarbenjamin commented
This is a good contribution. Thank you @namannimmo10. I'm merging this now.

2019-12-23 00:07 UTC, merged

2019-12-23 11:35 UTC, namannimmo10 commented
> This is a good contribution. Thank you @namannimmo10. I'm merging this now.

Thanks! Feels good ;)