Functions and test cases added
sympy/sympy pull request #18900
Opened 2020-03-18 12:21 UTC by Psycho-Pirate

#### References to other Issues or PRs

Fixes #16366

#### Brief description of what is fixed or changed
Area as an argument and area setter function was added in 2D beam class.
Functions to calculate shear stress and axial stress in 2D and 3D beams were added in beam.py
Test cases for shear and axial stress were added in test_beam.py

#### Other comments

#### Release Notes

NO ENTRY

2020-03-18 12:59 UTC, Psycho-Pirate commented
I always perform bin/test and bin/doctest, how should i check for trailing whitespace errors?

2020-03-19 07:16 UTC, Sc0rpi0n101 commented
> I always perform bin/test and bin/doctest, how should i check for trailing whitespace errors?

You can run the code quality test using `./bin/test quality` and remove the trailing whitespaces using `./bin/strip_whitespace <file>`.

You should check https://github.com/sympy/sympy/wiki/Development-workflow#be-sure-that-all-tests-of-sympy-pass for further reference.

2020-03-19 07:34 UTC, Sc0rpi0n101 requested changes
There are multiple instances of `self.area` and `self._area`. 
You should decide which one you want to use and change all the instances to use a single identifier.

2020-03-19 09:30 UTC, Psycho-Pirate commented
@Sc0rpi0n101 I have made the required changes. Please review.

2020-03-19 11:01 UTC, Psycho-Pirate commented
I have made the requested changes, please review @Sc0rpi0n101

2020-03-21 06:23 UTC, Smit-create commented on sympy/physics/continuum_mechanics/beam.py
>          >>> x, y, z = symbols('x, y, z')
Please add spaces around equal to sign.

2020-03-21 06:23 UTC, Smit-create commented on sympy/physics/continuum_mechanics/tests/test_beam.py
> +    q = -1*SingularityFunction(x, 2, 3)/3 + 1*SingularityFunction(x, 3, 1) + 1*SingularityFunction(x, 3, 2) + 1*SingularityFunction(x, 3, 3)/3
Please break these long lines with each line whitin 72 characters, using PEP8. Apply these to all long lines

2020-03-21 06:23 UTC, Smit-create commented on sympy/physics/continuum_mechanics/beam.py
>          """Initializes the class.
No need to add spaces around `=` in the function arguments.

2020-03-21 06:23 UTC, Smit-create commented on sympy/physics/continuum_mechanics/beam.py
> +
Correct it in the numpy doc format as:
```
area : Symbol/float 
      Represents the cross-section area of beam
```

2020-03-23 19:26 UTC, Sc0rpi0n101 reviewed
LGTM.
The tests are also passing.  
Can you add some more tests for the shear and axial stress for 3D beam?

Also, Can you squash your commits into one commit with a proper description of the changes?
You can check out https://github.com/sympy/sympy/wiki/Development-workflow#writing-commit-messages for reference

2020-03-23 20:53 UTC, Psycho-Pirate commented
I have squashed the commits.
I was planning on creating a function to plot shear and axial stress as part of my gsoc proposal, so i was thinking about adding more examples along with their plots later.
@Sc0rpi0n101

2020-03-24 15:47 UTC, Psycho-Pirate commented
> I have squashed the commits.
> I was planning on creating a function to plot shear and axial stress as part of my gsoc proposal, so i was thinking about adding more examples along with their plots later.

What do you suggest? @Sc0rpi0n101

2020-03-24 17:24 UTC, Sc0rpi0n101 commented
If you're planning to add more examples and tests later, then I think there is a fair amount of tests. :+1: 
Thank you for your contribution :)

2020-03-24 17:25 UTC, merged

2020-03-24 17:27 UTC, Sc0rpi0n101 commented
Ohh... I just realized it would've been better to have release notes for this change as the API is being changed and new functionalities are added. 

But since there's some time since the next release,  you can incliude these changes in your release notes for further changes. @Psycho-Pirate

2020-03-24 18:21 UTC, Psycho-Pirate commented
I have updated the release notes. Thanks for reviewing. :) @Sc0rpi0n101