Fix LaTeX printing of base-n logarithm
sympy/sympy pull request #19396
Opened 2020-05-22 09:54 UTC by sylee957

#### References to other Issues or PRs

#### Brief description of what is fixed or changed

#### Other comments

#### Release Notes

- printing
  - LaTeX printers will raise error when `ln_notation` is used with base-n logarithm.
  - LaTeX printers will print the base for base-n logarithm.

2020-05-25 07:39 UTC, eric-wieser commented on sympy/printing/latex.py
> +                    "'ln_notation'=True cannot be used because"
Shouldn't the setting just be ignored for this case?

2020-05-25 07:40 UTC, eric-wieser commented on sympy/printing/latex.py
> +                    "'ln_notation'=True cannot be used because"
Otherwise I have no way to print `ln x + log_2 y`

2020-05-25 08:03 UTC, eric-wieser commented on sympy/printing/latex.py
>          if not self._settings["ln_notation"]:
Can you flip the nesting of these if statements?
```
if a:
   if b:
       x()
   else:
       z()
else:
   if b:
       y()
   else:
       z()
```
is shorter as
```
if b:
   if a:
       x()
   else:
       y()
else:
   z()
```

2020-05-25 09:07 UTC, eric-wieser commented
Release note needs updating too.

2020-05-25 16:04 UTC, eric-wieser commented on sympy/printing/latex.py
> +        when the base is exponential constant.
Perhaps
```suggestion
        when the base is the exponential constant :math:`e`.
```

2020-05-25 16:07 UTC, eric-wieser commented on sympy/printing/latex.py
> +                tex = r"\log{\left(%s \right)}" % self._print(args[0])
Could use `self._add_parens` here

```suggestion
            if self._settings["ln_notation"]:
                tex = r"\ln{%s}" % self._add_parens(self._print(args[0]))
            else:
                tex = r"\log{%s}" % self._add_parens(self._print(args[0]))
```

Note that you'd need to remove some spaces from the LaTeX output test if you did this.

2020-05-25 16:07 UTC, eric-wieser approved these changes

2020-05-26 07:44 UTC, asmeurer commented
Wait, is this just for `log` created with `evaluate=False` or does it also try to detect log(x)/log(y)?

I'm actually surprised that `log(x, y, evaluate=False)` is allowed. Considering some of the issues described in https://github.com/sympy/sympy/issues/6888, I think it's problematic. I think we should address the underlying issues here before messing with the printing. 

The issue, to summarize, is that most code that looks for `log` in an expression implicitly assumes that it is base-e. For example:

```py
>>> diff(log(x, y, evaluate=False), x) 
1/x # WRONG!
>>> diff(log(x, y), x)
1/(x*log(y))
```

Since this permeates the code so much, I think it's potentially bad to even allow a 2-argument log, since any unfixed code would produce wrong results. I didn't realize that this was already happening with evaluate=False!

Rather, IMO it would be safer to add a new class, say called `LogBase`, that stores the base, but otherwise looks and behaves just like `log` to users, but to code that manipulates `log`, it wouldn't look like a `log` so that it doesn't do anything with it unless explicitly told to do so.

Even if we don't do this and rather just add a 2-arg to the existing `log`, I think we should remove `log(evaluate=False)` for now, as presently almost all code that deals with `log(x, y, evaluate=False)` is mathematically wrong, until we fix https://github.com/sympy/sympy/issues/6888 one way or the other. Since this PR basically legitimizes it, I am -1 to it based on the current state of things (but once we fix https://github.com/sympy/sympy/issues/6888 this PR itself looks fine).

2020-05-26 07:46 UTC, asmeurer requested changes
See https://github.com/sympy/sympy/pull/19396#issuecomment-633864890

2020-08-31 18:18 UTC, czgdp1807 commented
@sylee957 Are you still working on this? Or can it be taken by some other contributor?

2020-08-31 18:28 UTC, sylee957 commented
I’m not sure how to address @asmeurer’s comment for this
But if some people needs this fix, feel free to take over

2022-03-07 15:49 UTC, oscargus commented
The problem right now is that `log(4, 3, evaluate= False)` prints as `log(4)`, so that is clearly wrong. Hence, I cannot really see any problem with this (expect for the merge conflict). Sooner or later there will be a request for unevaluated printing of this as well.

Is this more wrong that pretty printing `log(4, 3)`?

2022-03-07 15:59 UTC, oscargus approved these changes

2023-08-23 10:19 UTC, closed without merging