3rd
sympy/sympy pull request #19987
Opened 2020-08-19 20:46 UTC by rijusougata13

Leading underscores and `latex()` bug fixed
#### References to other Issues or PRs

fixed  #14718

#### Brief description of what is fixed or changed

i have replaced the leading underscore with blank
#### Other comments

#### Release Notes

*printing
   * fixed leading underscored bug

2020-08-20 08:55 UTC, rijusougata13 commented
this can remove the '_' from begining

2020-08-21 11:34 UTC, eric-wieser requested changes
Please do not modify the `latex_escape` function. 
Its purpose is to escape latex, such that if you compile `latex_escape("a string_with_junk\%{")` to a pdf, you'll see exactly `a string_with_junk\%{` in the pdf.

The issue you are referencing is about `_print_Symbol` and friends, which do not even call this function.

2020-08-28 15:27 UTC, czgdp1807 commented on sympy/printing/latex.py
> +    s=s.replace('_','')
```suggestion
    s = s.replace('_', '')    
```

2020-08-28 15:36 UTC, eric-wieser commented on sympy/printing/latex.py
> +    s = s.replace('_', '')
```suggestion
    s = s.replace('_', '')
```

2020-08-28 16:40 UTC, rijusougata13 commented on sympy/printing/latex.py
> +    s=s.replace('_','')
i didn't get this you told me not to change that line .what should i do now?

2020-08-28 16:45 UTC, eric-wieser commented on sympy/printing/latex.py
> +    s=s.replace('_','')
You're right, my point here was just that if you fix the whitespace that causes the tests to not run at all, you'll see what the problem is:
```
_____________ sympy/printing/tests/test_latex.py:test_latex_escape _____________
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sympy-1.7.dev0-py3.8.egg/sympy/testing/runtests.py", line 1359, in _timeout
    function()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sympy-1.7.dev0-py3.8.egg/sympy/printing/tests/test_latex.py", line 2661, in test_latex_escape
    assert latex_escape(r"~^\&%$#_{}") == "".join([
AssertionError
```

The failing test is this one:

https://github.com/sympy/sympy/blob/e720a533224009d474f80e66a2e8327e3197b490/sympy/printing/tests/test_latex.py#L2660-L2672

> what should i do now?

You should read through the discussion in the original issue, and have a look at the proposed solution in #15939. The direction you're exploring at the moment is not the right one at all.

2020-08-28 17:57 UTC, rijusougata13 commented on sympy/printing/latex.py
> +    s=s.replace('_','')
oh ok ..sorry for being a beginner this github commits going over my head. i am confused wht to do next..i have to learn more about this githubs...thank you for helping me out

2020-12-05 07:00 UTC, czgdp1807 commented
@rijusougata13 Would you like to conclude this PR? The tests are failing, please fix them if so, otherwise do not close this PR. Thanks for your contributions.

2020-12-05 07:18 UTC, rijusougata13 commented
ok i am closing this pr

On Sat, 5 Dec, 2020, 12:30 pm Gagandeep Singh, <notifications@github.com>
wrote:

> @rijusougata13 <https://github.com/rijusougata13> Would you like to
> conclude this PR? The tests are failing, please fix them if so, otherwise
> do not close this PR. Thanks for your contributions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sympy/sympy/pull/19987#issuecomment-739136972>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMNRZE7LTWQWNAOT7WYOS2TSTHLCNANCNFSM4QFK4A7Q>
> .
>

2022-05-02 23:03 UTC, closed without merging