added area (=0) attribute to Segment2D class
sympy/sympy pull request #20469
Opened 2020-11-21 15:19 UTC by KatsuragiCSL

#### References to other Issues or PRs
Fixes #20460 

#### Brief description of what is fixed or changed
added area (=0) attribute to Segment2D class

2020-11-24 00:47 UTC, oscarbenjamin commented
Looks like the tests have failed because of trailing whitespace:
```
AssertionError: File contains trailing whitespace: /home/travis/build/sympy/sympy/sympy/geometry/line.py, line 2369.
```

2020-11-24 14:38 UTC, wsdookadr requested changes

2020-11-24 14:38 UTC, wsdookadr commented on sympy/geometry/line.py
> +
[The failing test](https://travis-ci.org/github/sympy/sympy/jobs/745076406#L325) is saying this training whitespace should be deleted.

2021-03-27 16:22 UTC, smichr commented
-1 
I don't think this is a good idea and gave reasons on the issue page.

2022-09-19 15:27 UTC, smichr commented
closing due to inactivity

2022-09-19 15:27 UTC, closed without merging