Update
sympy/sympy pull request #21484
Opened 2021-05-18 10:27 UTC by hackman01

updated README.md and setup.py

2021-05-19 08:35 UTC, namannimmo10 commented
Can you write "Fixes #21468" under the reference section? It automatically closes the issue once this gets in.

2021-05-19 10:28 UTC, Prateek93a commented on README.md
> -[![SymPy Banner](banner.svg)](https://sympy.org/)
I think there is no need for removing this line here. You can skip this line while reading it in `setup.py`

2021-05-19 11:38 UTC, Prateek93a requested changes

2021-05-19 12:14 UTC, namannimmo10 commented on setup.py
> +          long_description = f.read()
One option is to use `.split("\n")` to separate the lines and then join the lines excluding the banner.

2021-05-19 12:52 UTC, oscarbenjamin commented on setup.py
> +          long_description = f.read()
I think it would be better just to use an absolute URL for the banner image:
https://github.com/sympy/sympy/raw/master/banner.svg

2021-05-19 13:27 UTC, hackman01 commented on setup.py
> +          long_description = f.read()
**@oscarbenjamin** I think you are right, I had updated README.md accordingly.

2021-05-19 13:57 UTC, hackman01 commented on setup.py
> +          long_description = f.read()
@Prateek93a Placed the code for reading the file above but not skipped line containing banner as I added the absolute URL in that line.

2021-05-20 03:56 UTC, hackman01 commented on setup.py
> +          long_description = f.read()
I am adding banner's absolute URL, do I still need to add long_description in setup

2021-05-20 05:37 UTC, Prateek93a commented on setup.py
> +          long_description = f.read()
Nope, `setup.cfg` file has meta tag to load `long_description`. So I believe you don't need it in `setup.py`.

2021-05-20 13:21 UTC, hackman01 commented on setup.py
> +          long_description = f.read()
If it was there then why we were adding it in `setup.py` , I mean how will the preference be decided among  `setup.cfg` or `setup.py`, or we will have to remove `long_description` from `setup.cfg` after adding it in `setup.py` .

2021-05-20 13:25 UTC, hackman01 commented
1 workflow awaiting approval
please approve it.

2021-05-20 13:29 UTC, oscarbenjamin commented
The changes to setup.py are not needed and the commits should be squashed.

2021-05-23 03:07 UTC, hackman01 commented
reseted setup.py and changed to single commit

2021-05-23 03:23 UTC, hackman01 commented
reseted `setup.py` and changed to single commit

2021-05-28 14:04 UTC, merged