Fixed #23880
sympy/sympy pull request #23917
Opened 2022-08-12 11:41 UTC by metabiswadeep

####  Fixed #23880

#### Added text about general case use of  reduce_inequalities.

#### Release Notes

- other
  - an addition to documentation about inequalities solver.

2022-08-17 23:52 UTC, bertiewooster requested changes
Thanks for doing this!

2022-08-17 23:52 UTC, bertiewooster commented on doc/src/modules/solvers/inequalities.rst
> +For general cases the reduce_equalities function should be used.
```suggestion
For general cases :func:`~.reduce_equalities` should be used.
```

Just adding a link to the cited function, so visitors can jump directly to it.

2022-08-17 23:52 UTC, bertiewooster commented on doc/src/modules/solvers/inequalities.rst
> +Other functions are the subcategories useful for special dedicated operations.
```suggestion
Other functions are the subcategories useful for special dedicated operations, and will be called internally as needed by ``reduce_equalities``.
```

2022-08-18 11:57 UTC, metabiswadeep commented
Thanks for the suggestions @bertiewooster .

2022-09-08 21:06 UTC, asmeurer commented
@bertiewooster do you think this is ready to be merged?

2022-09-08 21:11 UTC, bertiewooster commented
@asmeurer yes

2022-09-08 22:42 UTC, merged