Mentioned that Float cannot represent negative zero
sympy/sympy pull request #24137
Opened 2022-10-15 09:50 UTC by metabiswadeep

####  Fixed #24088 

#### Improved documentation of float to include that Float cannot represent negative zero.

#### Release Notes

- other
  - an addition to documentation about Float.

2022-10-16 09:23 UTC, oscargus commented
Please move this to the Note section.

2022-10-16 12:28 UTC, oscargus commented
I suggest that you put it last. Now it is in the middle of the approximation discussion.

2022-10-18 05:05 UTC, chatcannon commented on sympy/core/numbers.py
> +    Zero in Float only has a single value. Values are not seperate for positive and neghative zeroes.
```suggestion
    Zero in Float only has a single value. Values are not separate for positive and negative zeroes.
```

2022-10-18 05:06 UTC, chatcannon requested changes
I spotted some typos but otherwise it is what I was looking for.

2022-10-23 09:22 UTC, merged