Stats: Fixed variance of sum of Poisson Random Variables
sympy/sympy pull request #24682
Opened 2023-02-08 06:31 UTC by prototypevito

#### References to other Issues or PRs

Fixes #20669

#### Brief description of what is fixed or changed
-> This commit does not include the type change of  r to int but solves the problem that followed: the code returning an unevaluated limit
-> The problem lay in the summations.py file, where the existing code could only detect if the number was a float and could not check for float numbers present in a fraction like (7.5)/x+1.  The same has been fixed.
#### Other comments

#### Release Notes

2023-02-09 06:27 UTC, prototypevito commented
This commit also fixes the issue: Finding the expected value of the product of two random variables with floating type parameters. 
How I arrived at the solution? 
Upon comparing the two cases (using an integer as the parameter for Poisson and then using a floating type), the workflow was identical for both **until**  `numer, denom = fraction(factor(hs))` in **summations.py** at which the float type case could not be factorized. This should have been taken care of by the line `if isinstance(hs, Float)` but the instance function returns False for cases where only a part of the input is a float. 
For example:
`if isinstance(5.0, Float)` gives `True` 
but
`if isinstance(5.0/(x+1), Float)` gives `False`, x being a variable

Hence the change proposed works. @czgdp1807 let me know if this is the right way of solving this issue.

2023-02-09 10:59 UTC, czgdp1807 requested changes
Please add a regression test for the fix. Then I would be able to review it more thoroughly. Thanks for sending the PR. :-)

2023-02-13 10:38 UTC, prototypevito commented
> Please add a regression test for the fix. Then I would be able to review it more thoroughly. Thanks for sending the PR. :-)

Hey, I have added a test. Let me know if the test is appropriate.

2023-02-15 04:26 UTC, czgdp1807 approved these changes
Other than this looks good to me. @Upabjojr thoughts?

2023-02-15 04:26 UTC, czgdp1807 commented on sympy/stats/tests/test_rv.py
> +    assert N(E(X1*X3),7)==N(E(X1)*E(X3),7)
```suggestion
    assert N(variance(X1 + X2), 7) == N(variance(X1) + variance(X2), 7)
    assert N(E(X1*X2), 7) == N(E(X1) * E(X2), 7)
    assert N(E(X1*X3), 7) == N(E(X1) * E(X3), 7)
```

2023-02-15 10:54 UTC, prototypevito commented
@oscarbenjamin I have added my Name and email ID to the authors file, but it still gives a test error. Is it because none of my pull requests have been merged yet? Because when I run mailmap_check.py on my local device, it does not give me an error.

2023-02-20 05:23 UTC, prototypevito commented
> Other than this looks good to me. @Upabjojr thoughts?

@Upabjojr Kindly let me know if there is anything else to be changed. Thanks!

2023-02-28 12:02 UTC, closed without merging