nonlinsolve returns duplicate solution
sympy/sympy pull request #26342
Opened 2024-03-10 13:45 UTC by HAWK1704

Worked on [nonlinear-returns-duplicate-solution](https://github.com/sympy/sympy/issues/13961) and made some minor changes by adding a code block.

I have added a try-expect block in code in which I am expanding the terms , then pushing them into FiniteSet().

2024-03-10 14:22 UTC, oscarbenjamin commented
> The following commits **add new files**:

The commits will need to be squashed to remove this.

2024-03-11 00:35 UTC, samithkavishke requested changes

2024-03-11 00:35 UTC, samithkavishke commented on sympy/solvers/solveset.py
> +    # poly_sol=expand(x) for x in poly_sol
remove these comments

2024-03-11 07:40 UTC, HAWK1704 commented
I want to ask that should I write a separate function for expand the solution terms using recursion or should I leave the solution here?

If you want me to write a function then can you provide me some data like how we are expecting the solutions, like the solution I worked on was FiniteSet(Tuple()) type. What I mean is that can I expect solutions like FiniteSet(Tuple(Tuple())), FiniteSet(Tuple(Tuple(Tuple()))), etc,.

2024-03-11 20:06 UTC, HAWK1704 commented
> I want to ask that should I write a separate function for expand the solution terms using recursion or should I leave the solution here?
> 
> If you want me to write a function then can you provide me some data like how we are expecting the solutions, like the solution I worked on was FiniteSet(Tuple()) type. What I mean is that can I expect solutions like FiniteSet(Tuple(Tuple())), FiniteSet(Tuple(Tuple(Tuple()))), etc,.

Worked on this Idea so verify it once.

2024-03-16 16:04 UTC, smichr commented
There should be a test for which the solution would have duplicates in master but not in this branch. Fictitious example:
```python
def test_no_dup-nonlinsolve():
    assert nonlinsolve(x**2-4) == {-2, 2}  <-- in master {-2, 2, 2*(cos(1)**2 + sin(1)**2)}
```

2024-03-16 16:34 UTC, samithkavishke requested changes
You must add a test case to verify this code.

2024-03-16 20:20 UTC, HAWK1704 commented
I'll look into that after my exams over.

2024-03-16 23:09 UTC, smichr commented on sympy/solvers/solveset.py
> +def expand_and_simplify(subs_res):
`simplify` should not be used (in general) to fix very specific problems. As pointed out in the issue, the problem stems from how 2-arg Adds are handled. Apparently, two different code paths produced the same solution but did so in a different way and one leaves a negative one factored out while the other has it distributed. One solution is to just patch things up here with a routine like
```python
def touchup(sol):
    # put the minimal simplification needed to keep duplicate
    # solutions from appearing in the solution
    return bottom_up(sol, signsimp)
```
(and import bottom_up on the line importing from traversal).

A better solution would be to track down why these two expressions are being constructed in two different ways and see if they should be doing things the same way or using common code.

The best solution would be to disable distribution of the constant onto an Add (but that is a very involved task).

2024-03-23 13:01 UTC, HAWK1704 commented
how to resolve ``doctest-latest`` and ``authors`` failure?

2024-03-25 01:46 UTC, closed without merging