Fix reference
sympy/sympy pull request #26851
Opened 2024-07-24 13:54 UTC by William-nyarash

Fix broken link to Diophantine solver guide

Updated the link in doc/src/modules/solvers/diophantine to point to the correct guide at https://github.com/sympy/sympy/blob/master/doc/src/guides/solving/solve-diophantine-equation.md.

2024-07-24 14:56 UTC, sylee957 commented
Which kind of reference problem are you going to fix? Do you have any link to the issue?

2024-07-28 11:36 UTC, Shekharrajak requested changes

2024-07-28 11:36 UTC, Shekharrajak commented on doc/src/guides/solving/solve-diophantine-equation.md
> +<!-- (solving-guide-diophantine)= -->
Why this is commented ?

2024-07-28 12:14 UTC, sylee957 commented
I'm closing this because this is not working and the author does not respond to the feedback,
and I'm suspecting that this PR could generated by some bot or LLM because the content looks duplicate.

2024-07-28 12:14 UTC, closed without merging